// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AdminSessionsColumns holds the columns for the "admin_sessions" table.
	AdminSessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "session_id", Type: field.TypeString, Unique: true},
		{Name: "username", Type: field.TypeString},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "last_seen", Type: field.TypeTime},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AdminSessionsTable holds the schema information for the "admin_sessions" table.
	AdminSessionsTable = &schema.Table{
		Name:       "admin_sessions",
		Columns:    AdminSessionsColumns,
		PrimaryKey: []*schema.Column{AdminSessionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "adminsession_username",
				Unique:  false,
				Columns: []*schema.Column{AdminSessionsColumns[2]},
			},
			{
				Name:    "adminsession_expires_at",
				Unique:  false,
				Columns: []*schema.Column{AdminSessionsColumns[3]},
			},
		},
	}
	// AdminUsersColumns holds the columns for the "admin_users" table.
	AdminUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AdminUsersTable holds the schema information for the "admin_users" table.
	AdminUsersTable = &schema.Table{
		Name:       "admin_users",
		Columns:    AdminUsersColumns,
		PrimaryKey: []*schema.Column{AdminUsersColumns[0]},
	}
	// AuditEventsColumns holds the columns for the "audit_events" table.
	AuditEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "actor", Type: field.TypeString, Default: "system"},
		{Name: "action", Type: field.TypeString},
		{Name: "target", Type: field.TypeString, Default: ""},
		{Name: "detail", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AuditEventsTable holds the schema information for the "audit_events" table.
	AuditEventsTable = &schema.Table{
		Name:       "audit_events",
		Columns:    AuditEventsColumns,
		PrimaryKey: []*schema.Column{AuditEventsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "auditevent_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuditEventsColumns[5]},
			},
			{
				Name:    "auditevent_action",
				Unique:  false,
				Columns: []*schema.Column{AuditEventsColumns[2]},
			},
		},
	}
	// ClusterSettingsColumns holds the columns for the "cluster_settings" table.
	ClusterSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "key", Type: field.TypeString, Unique: true},
		{Name: "value", Type: field.TypeString, Default: ""},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ClusterSettingsTable holds the schema information for the "cluster_settings" table.
	ClusterSettingsTable = &schema.Table{
		Name:       "cluster_settings",
		Columns:    ClusterSettingsColumns,
		PrimaryKey: []*schema.Column{ClusterSettingsColumns[0]},
	}
	// NodesColumns holds the columns for the "nodes" table.
	NodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "node_id", Type: field.TypeString, Unique: true},
		{Name: "ssh_server", Type: field.TypeString, Default: ""},
		{Name: "public_base_url", Type: field.TypeString, Default: ""},
		{Name: "weight", Type: field.TypeInt, Default: 100},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "maintenance", Type: field.TypeBool, Default: false},
		{Name: "max_tunnels", Type: field.TypeInt, Default: 100000},
		{Name: "current_tunnels", Type: field.TypeInt, Default: 0},
		{Name: "max_active_connections", Type: field.TypeInt, Default: 0},
		{Name: "active_connections", Type: field.TypeInt, Default: 0},
		{Name: "region", Type: field.TypeString, Default: "default"},
		{Name: "token", Type: field.TypeString, Default: ""},
		{Name: "last_heartbeat", Type: field.TypeTime},
		{Name: "is_local", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// NodesTable holds the schema information for the "nodes" table.
	NodesTable = &schema.Table{
		Name:       "nodes",
		Columns:    NodesColumns,
		PrimaryKey: []*schema.Column{NodesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "node_enabled_maintenance",
				Unique:  false,
				Columns: []*schema.Column{NodesColumns[5], NodesColumns[6]},
			},
			{
				Name:    "node_last_heartbeat",
				Unique:  false,
				Columns: []*schema.Column{NodesColumns[13]},
			},
		},
	}
	// RoutesColumns holds the columns for the "routes" table.
	RoutesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token", Type: field.TypeString, Unique: true},
		{Name: "node_id", Type: field.TypeString},
		{Name: "target_url", Type: field.TypeString},
		{Name: "public_url", Type: field.TypeString},
		{Name: "peer_id", Type: field.TypeString, Default: ""},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
	}
	// RoutesTable holds the schema information for the "routes" table.
	RoutesTable = &schema.Table{
		Name:       "routes",
		Columns:    RoutesColumns,
		PrimaryKey: []*schema.Column{RoutesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "route_node_id",
				Unique:  false,
				Columns: []*schema.Column{RoutesColumns[2]},
			},
			{
				Name:    "route_status_expires_at",
				Unique:  false,
				Columns: []*schema.Column{RoutesColumns[6], RoutesColumns[9]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AdminSessionsTable,
		AdminUsersTable,
		AuditEventsTable,
		ClusterSettingsTable,
		NodesTable,
		RoutesTable,
	}
)

func init() {
}
