// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"localshare/internal/store/ent/adminsession"
	"localshare/internal/store/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdminSessionDelete is the builder for deleting a AdminSession entity.
type AdminSessionDelete struct {
	config
	hooks    []Hook
	mutation *AdminSessionMutation
}

// Where appends a list predicates to the AdminSessionDelete builder.
func (_d *AdminSessionDelete) Where(ps ...predicate.AdminSession) *AdminSessionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AdminSessionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdminSessionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AdminSessionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(adminsession.Table, sqlgraph.NewFieldSpec(adminsession.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AdminSessionDeleteOne is the builder for deleting a single AdminSession entity.
type AdminSessionDeleteOne struct {
	_d *AdminSessionDelete
}

// Where appends a list predicates to the AdminSessionDelete builder.
func (_d *AdminSessionDeleteOne) Where(ps ...predicate.AdminSession) *AdminSessionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AdminSessionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{adminsession.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AdminSessionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
