// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"localshare/internal/store/ent/adminsession"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdminSessionCreate is the builder for creating a AdminSession entity.
type AdminSessionCreate struct {
	config
	mutation *AdminSessionMutation
	hooks    []Hook
}

// SetSessionID sets the "session_id" field.
func (_c *AdminSessionCreate) SetSessionID(v string) *AdminSessionCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetUsername sets the "username" field.
func (_c *AdminSessionCreate) SetUsername(v string) *AdminSessionCreate {
	_c.mutation.SetUsername(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *AdminSessionCreate) SetExpiresAt(v time.Time) *AdminSessionCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetLastSeen sets the "last_seen" field.
func (_c *AdminSessionCreate) SetLastSeen(v time.Time) *AdminSessionCreate {
	_c.mutation.SetLastSeen(v)
	return _c
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_c *AdminSessionCreate) SetNillableLastSeen(v *time.Time) *AdminSessionCreate {
	if v != nil {
		_c.SetLastSeen(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AdminSessionCreate) SetCreatedAt(v time.Time) *AdminSessionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AdminSessionCreate) SetNillableCreatedAt(v *time.Time) *AdminSessionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the AdminSessionMutation object of the builder.
func (_c *AdminSessionCreate) Mutation() *AdminSessionMutation {
	return _c.mutation
}

// Save creates the AdminSession in the database.
func (_c *AdminSessionCreate) Save(ctx context.Context) (*AdminSession, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AdminSessionCreate) SaveX(ctx context.Context) *AdminSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminSessionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminSessionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AdminSessionCreate) defaults() {
	if _, ok := _c.mutation.LastSeen(); !ok {
		v := adminsession.DefaultLastSeen()
		_c.mutation.SetLastSeen(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := adminsession.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AdminSessionCreate) check() error {
	if _, ok := _c.mutation.SessionID(); !ok {
		return &ValidationError{Name: "session_id", err: errors.New(`ent: missing required field "AdminSession.session_id"`)}
	}
	if v, ok := _c.mutation.SessionID(); ok {
		if err := adminsession.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "AdminSession.session_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "AdminSession.username"`)}
	}
	if v, ok := _c.mutation.Username(); ok {
		if err := adminsession.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "AdminSession.username": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "AdminSession.expires_at"`)}
	}
	if _, ok := _c.mutation.LastSeen(); !ok {
		return &ValidationError{Name: "last_seen", err: errors.New(`ent: missing required field "AdminSession.last_seen"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AdminSession.created_at"`)}
	}
	return nil
}

func (_c *AdminSessionCreate) sqlSave(ctx context.Context) (*AdminSession, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AdminSessionCreate) createSpec() (*AdminSession, *sqlgraph.CreateSpec) {
	var (
		_node = &AdminSession{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(adminsession.Table, sqlgraph.NewFieldSpec(adminsession.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(adminsession.FieldSessionID, field.TypeString, value)
		_node.SessionID = value
	}
	if value, ok := _c.mutation.Username(); ok {
		_spec.SetField(adminsession.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(adminsession.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.LastSeen(); ok {
		_spec.SetField(adminsession.FieldLastSeen, field.TypeTime, value)
		_node.LastSeen = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(adminsession.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// AdminSessionCreateBulk is the builder for creating many AdminSession entities in bulk.
type AdminSessionCreateBulk struct {
	config
	err      error
	builders []*AdminSessionCreate
}

// Save creates the AdminSession entities in the database.
func (_c *AdminSessionCreateBulk) Save(ctx context.Context) ([]*AdminSession, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AdminSession, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AdminSessionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AdminSessionCreateBulk) SaveX(ctx context.Context) []*AdminSession {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AdminSessionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AdminSessionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
