// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"localshare/internal/store/ent/adminsession"
	"localshare/internal/store/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AdminSessionUpdate is the builder for updating AdminSession entities.
type AdminSessionUpdate struct {
	config
	hooks    []Hook
	mutation *AdminSessionMutation
}

// Where appends a list predicates to the AdminSessionUpdate builder.
func (_u *AdminSessionUpdate) Where(ps ...predicate.AdminSession) *AdminSessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *AdminSessionUpdate) SetSessionID(v string) *AdminSessionUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AdminSessionUpdate) SetNillableSessionID(v *string) *AdminSessionUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *AdminSessionUpdate) SetUsername(v string) *AdminSessionUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *AdminSessionUpdate) SetNillableUsername(v *string) *AdminSessionUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AdminSessionUpdate) SetExpiresAt(v time.Time) *AdminSessionUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AdminSessionUpdate) SetNillableExpiresAt(v *time.Time) *AdminSessionUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *AdminSessionUpdate) SetLastSeen(v time.Time) *AdminSessionUpdate {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *AdminSessionUpdate) SetNillableLastSeen(v *time.Time) *AdminSessionUpdate {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// Mutation returns the AdminSessionMutation object of the builder.
func (_u *AdminSessionUpdate) Mutation() *AdminSessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AdminSessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminSessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AdminSessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminSessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminSessionUpdate) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := adminsession.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "AdminSession.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := adminsession.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "AdminSession.username": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminSessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminsession.Table, adminsession.Columns, sqlgraph.NewFieldSpec(adminsession.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(adminsession.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(adminsession.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(adminsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(adminsession.FieldLastSeen, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AdminSessionUpdateOne is the builder for updating a single AdminSession entity.
type AdminSessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AdminSessionMutation
}

// SetSessionID sets the "session_id" field.
func (_u *AdminSessionUpdateOne) SetSessionID(v string) *AdminSessionUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *AdminSessionUpdateOne) SetNillableSessionID(v *string) *AdminSessionUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetUsername sets the "username" field.
func (_u *AdminSessionUpdateOne) SetUsername(v string) *AdminSessionUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *AdminSessionUpdateOne) SetNillableUsername(v *string) *AdminSessionUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AdminSessionUpdateOne) SetExpiresAt(v time.Time) *AdminSessionUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AdminSessionUpdateOne) SetNillableExpiresAt(v *time.Time) *AdminSessionUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetLastSeen sets the "last_seen" field.
func (_u *AdminSessionUpdateOne) SetLastSeen(v time.Time) *AdminSessionUpdateOne {
	_u.mutation.SetLastSeen(v)
	return _u
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (_u *AdminSessionUpdateOne) SetNillableLastSeen(v *time.Time) *AdminSessionUpdateOne {
	if v != nil {
		_u.SetLastSeen(*v)
	}
	return _u
}

// Mutation returns the AdminSessionMutation object of the builder.
func (_u *AdminSessionUpdateOne) Mutation() *AdminSessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the AdminSessionUpdate builder.
func (_u *AdminSessionUpdateOne) Where(ps ...predicate.AdminSession) *AdminSessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AdminSessionUpdateOne) Select(field string, fields ...string) *AdminSessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AdminSession entity.
func (_u *AdminSessionUpdateOne) Save(ctx context.Context) (*AdminSession, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AdminSessionUpdateOne) SaveX(ctx context.Context) *AdminSession {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AdminSessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AdminSessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AdminSessionUpdateOne) check() error {
	if v, ok := _u.mutation.SessionID(); ok {
		if err := adminsession.SessionIDValidator(v); err != nil {
			return &ValidationError{Name: "session_id", err: fmt.Errorf(`ent: validator failed for field "AdminSession.session_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := adminsession.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "AdminSession.username": %w`, err)}
		}
	}
	return nil
}

func (_u *AdminSessionUpdateOne) sqlSave(ctx context.Context) (_node *AdminSession, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(adminsession.Table, adminsession.Columns, sqlgraph.NewFieldSpec(adminsession.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AdminSession.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, adminsession.FieldID)
		for _, f := range fields {
			if !adminsession.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != adminsession.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(adminsession.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(adminsession.FieldUsername, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(adminsession.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastSeen(); ok {
		_spec.SetField(adminsession.FieldLastSeen, field.TypeTime, value)
	}
	_node = &AdminSession{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{adminsession.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
