// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"localshare/internal/store/ent/auditevent"
	"localshare/internal/store/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuditEventUpdate is the builder for updating AuditEvent entities.
type AuditEventUpdate struct {
	config
	hooks    []Hook
	mutation *AuditEventMutation
}

// Where appends a list predicates to the AuditEventUpdate builder.
func (_u *AuditEventUpdate) Where(ps ...predicate.AuditEvent) *AuditEventUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetActor sets the "actor" field.
func (_u *AuditEventUpdate) SetActor(v string) *AuditEventUpdate {
	_u.mutation.SetActor(v)
	return _u
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_u *AuditEventUpdate) SetNillableActor(v *string) *AuditEventUpdate {
	if v != nil {
		_u.SetActor(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditEventUpdate) SetAction(v string) *AuditEventUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditEventUpdate) SetNillableAction(v *string) *AuditEventUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *AuditEventUpdate) SetTarget(v string) *AuditEventUpdate {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *AuditEventUpdate) SetNillableTarget(v *string) *AuditEventUpdate {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetDetail sets the "detail" field.
func (_u *AuditEventUpdate) SetDetail(v map[string]interface{}) *AuditEventUpdate {
	_u.mutation.SetDetail(v)
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *AuditEventUpdate) ClearDetail() *AuditEventUpdate {
	_u.mutation.ClearDetail()
	return _u
}

// Mutation returns the AuditEventMutation object of the builder.
func (_u *AuditEventUpdate) Mutation() *AuditEventMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuditEventUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditEventUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuditEventUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditEventUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditEventUpdate) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := auditevent.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditEvent.action": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditEventUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditevent.Table, auditevent.Columns, sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Actor(); ok {
		_spec.SetField(auditevent.FieldActor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditevent.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(auditevent.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(auditevent.FieldDetail, field.TypeJSON, value)
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(auditevent.FieldDetail, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuditEventUpdateOne is the builder for updating a single AuditEvent entity.
type AuditEventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuditEventMutation
}

// SetActor sets the "actor" field.
func (_u *AuditEventUpdateOne) SetActor(v string) *AuditEventUpdateOne {
	_u.mutation.SetActor(v)
	return _u
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_u *AuditEventUpdateOne) SetNillableActor(v *string) *AuditEventUpdateOne {
	if v != nil {
		_u.SetActor(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *AuditEventUpdateOne) SetAction(v string) *AuditEventUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *AuditEventUpdateOne) SetNillableAction(v *string) *AuditEventUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTarget sets the "target" field.
func (_u *AuditEventUpdateOne) SetTarget(v string) *AuditEventUpdateOne {
	_u.mutation.SetTarget(v)
	return _u
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_u *AuditEventUpdateOne) SetNillableTarget(v *string) *AuditEventUpdateOne {
	if v != nil {
		_u.SetTarget(*v)
	}
	return _u
}

// SetDetail sets the "detail" field.
func (_u *AuditEventUpdateOne) SetDetail(v map[string]interface{}) *AuditEventUpdateOne {
	_u.mutation.SetDetail(v)
	return _u
}

// ClearDetail clears the value of the "detail" field.
func (_u *AuditEventUpdateOne) ClearDetail() *AuditEventUpdateOne {
	_u.mutation.ClearDetail()
	return _u
}

// Mutation returns the AuditEventMutation object of the builder.
func (_u *AuditEventUpdateOne) Mutation() *AuditEventMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuditEventUpdate builder.
func (_u *AuditEventUpdateOne) Where(ps ...predicate.AuditEvent) *AuditEventUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuditEventUpdateOne) Select(field string, fields ...string) *AuditEventUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuditEvent entity.
func (_u *AuditEventUpdateOne) Save(ctx context.Context) (*AuditEvent, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuditEventUpdateOne) SaveX(ctx context.Context) *AuditEvent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuditEventUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuditEventUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuditEventUpdateOne) check() error {
	if v, ok := _u.mutation.Action(); ok {
		if err := auditevent.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditEvent.action": %w`, err)}
		}
	}
	return nil
}

func (_u *AuditEventUpdateOne) sqlSave(ctx context.Context) (_node *AuditEvent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(auditevent.Table, auditevent.Columns, sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuditEvent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, auditevent.FieldID)
		for _, f := range fields {
			if !auditevent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != auditevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Actor(); ok {
		_spec.SetField(auditevent.FieldActor, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(auditevent.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Target(); ok {
		_spec.SetField(auditevent.FieldTarget, field.TypeString, value)
	}
	if value, ok := _u.mutation.Detail(); ok {
		_spec.SetField(auditevent.FieldDetail, field.TypeJSON, value)
	}
	if _u.mutation.DetailCleared() {
		_spec.ClearField(auditevent.FieldDetail, field.TypeJSON)
	}
	_node = &AuditEvent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{auditevent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
