// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"localshare/internal/store/ent/auditevent"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuditEventCreate is the builder for creating a AuditEvent entity.
type AuditEventCreate struct {
	config
	mutation *AuditEventMutation
	hooks    []Hook
}

// SetActor sets the "actor" field.
func (_c *AuditEventCreate) SetActor(v string) *AuditEventCreate {
	_c.mutation.SetActor(v)
	return _c
}

// SetNillableActor sets the "actor" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableActor(v *string) *AuditEventCreate {
	if v != nil {
		_c.SetActor(*v)
	}
	return _c
}

// SetAction sets the "action" field.
func (_c *AuditEventCreate) SetAction(v string) *AuditEventCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetTarget sets the "target" field.
func (_c *AuditEventCreate) SetTarget(v string) *AuditEventCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetNillableTarget sets the "target" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableTarget(v *string) *AuditEventCreate {
	if v != nil {
		_c.SetTarget(*v)
	}
	return _c
}

// SetDetail sets the "detail" field.
func (_c *AuditEventCreate) SetDetail(v map[string]interface{}) *AuditEventCreate {
	_c.mutation.SetDetail(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AuditEventCreate) SetCreatedAt(v time.Time) *AuditEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AuditEventCreate) SetNillableCreatedAt(v *time.Time) *AuditEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the AuditEventMutation object of the builder.
func (_c *AuditEventCreate) Mutation() *AuditEventMutation {
	return _c.mutation
}

// Save creates the AuditEvent in the database.
func (_c *AuditEventCreate) Save(ctx context.Context) (*AuditEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AuditEventCreate) SaveX(ctx context.Context) *AuditEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AuditEventCreate) defaults() {
	if _, ok := _c.mutation.Actor(); !ok {
		v := auditevent.DefaultActor
		_c.mutation.SetActor(v)
	}
	if _, ok := _c.mutation.Target(); !ok {
		v := auditevent.DefaultTarget
		_c.mutation.SetTarget(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := auditevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AuditEventCreate) check() error {
	if _, ok := _c.mutation.Actor(); !ok {
		return &ValidationError{Name: "actor", err: errors.New(`ent: missing required field "AuditEvent.actor"`)}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "AuditEvent.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := auditevent.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "AuditEvent.action": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "AuditEvent.target"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AuditEvent.created_at"`)}
	}
	return nil
}

func (_c *AuditEventCreate) sqlSave(ctx context.Context) (*AuditEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AuditEventCreate) createSpec() (*AuditEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &AuditEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(auditevent.Table, sqlgraph.NewFieldSpec(auditevent.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Actor(); ok {
		_spec.SetField(auditevent.FieldActor, field.TypeString, value)
		_node.Actor = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(auditevent.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(auditevent.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.Detail(); ok {
		_spec.SetField(auditevent.FieldDetail, field.TypeJSON, value)
		_node.Detail = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(auditevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// AuditEventCreateBulk is the builder for creating many AuditEvent entities in bulk.
type AuditEventCreateBulk struct {
	config
	err      error
	builders []*AuditEventCreate
}

// Save creates the AuditEvent entities in the database.
func (_c *AuditEventCreateBulk) Save(ctx context.Context) ([]*AuditEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AuditEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuditEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AuditEventCreateBulk) SaveX(ctx context.Context) []*AuditEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AuditEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AuditEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
