// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"localshare/internal/store/ent/clustersetting"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClusterSettingCreate is the builder for creating a ClusterSetting entity.
type ClusterSettingCreate struct {
	config
	mutation *ClusterSettingMutation
	hooks    []Hook
}

// SetKey sets the "key" field.
func (_c *ClusterSettingCreate) SetKey(v string) *ClusterSettingCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *ClusterSettingCreate) SetValue(v string) *ClusterSettingCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *ClusterSettingCreate) SetNillableValue(v *string) *ClusterSettingCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ClusterSettingCreate) SetUpdatedAt(v time.Time) *ClusterSettingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ClusterSettingCreate) SetNillableUpdatedAt(v *time.Time) *ClusterSettingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the ClusterSettingMutation object of the builder.
func (_c *ClusterSettingCreate) Mutation() *ClusterSettingMutation {
	return _c.mutation
}

// Save creates the ClusterSetting in the database.
func (_c *ClusterSettingCreate) Save(ctx context.Context) (*ClusterSetting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ClusterSettingCreate) SaveX(ctx context.Context) *ClusterSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClusterSettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClusterSettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ClusterSettingCreate) defaults() {
	if _, ok := _c.mutation.Value(); !ok {
		v := clustersetting.DefaultValue
		_c.mutation.SetValue(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := clustersetting.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ClusterSettingCreate) check() error {
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "ClusterSetting.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := clustersetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ClusterSetting.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "ClusterSetting.value"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ClusterSetting.updated_at"`)}
	}
	return nil
}

func (_c *ClusterSettingCreate) sqlSave(ctx context.Context) (*ClusterSetting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ClusterSettingCreate) createSpec() (*ClusterSetting, *sqlgraph.CreateSpec) {
	var (
		_node = &ClusterSetting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(clustersetting.Table, sqlgraph.NewFieldSpec(clustersetting.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(clustersetting.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(clustersetting.FieldValue, field.TypeString, value)
		_node.Value = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(clustersetting.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// ClusterSettingCreateBulk is the builder for creating many ClusterSetting entities in bulk.
type ClusterSettingCreateBulk struct {
	config
	err      error
	builders []*ClusterSettingCreate
}

// Save creates the ClusterSetting entities in the database.
func (_c *ClusterSettingCreateBulk) Save(ctx context.Context) ([]*ClusterSetting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ClusterSetting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClusterSettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ClusterSettingCreateBulk) SaveX(ctx context.Context) []*ClusterSetting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ClusterSettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ClusterSettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
