// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"localshare/internal/store/ent/clustersetting"
	"localshare/internal/store/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClusterSettingDelete is the builder for deleting a ClusterSetting entity.
type ClusterSettingDelete struct {
	config
	hooks    []Hook
	mutation *ClusterSettingMutation
}

// Where appends a list predicates to the ClusterSettingDelete builder.
func (_d *ClusterSettingDelete) Where(ps ...predicate.ClusterSetting) *ClusterSettingDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ClusterSettingDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ClusterSettingDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ClusterSettingDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(clustersetting.Table, sqlgraph.NewFieldSpec(clustersetting.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ClusterSettingDeleteOne is the builder for deleting a single ClusterSetting entity.
type ClusterSettingDeleteOne struct {
	_d *ClusterSettingDelete
}

// Where appends a list predicates to the ClusterSettingDelete builder.
func (_d *ClusterSettingDeleteOne) Where(ps ...predicate.ClusterSetting) *ClusterSettingDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ClusterSettingDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{clustersetting.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ClusterSettingDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
