// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"localshare/internal/store/ent/clustersetting"
	"localshare/internal/store/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClusterSettingUpdate is the builder for updating ClusterSetting entities.
type ClusterSettingUpdate struct {
	config
	hooks    []Hook
	mutation *ClusterSettingMutation
}

// Where appends a list predicates to the ClusterSettingUpdate builder.
func (_u *ClusterSettingUpdate) Where(ps ...predicate.ClusterSetting) *ClusterSettingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKey sets the "key" field.
func (_u *ClusterSettingUpdate) SetKey(v string) *ClusterSettingUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *ClusterSettingUpdate) SetNillableKey(v *string) *ClusterSettingUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *ClusterSettingUpdate) SetValue(v string) *ClusterSettingUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *ClusterSettingUpdate) SetNillableValue(v *string) *ClusterSettingUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ClusterSettingUpdate) SetUpdatedAt(v time.Time) *ClusterSettingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ClusterSettingMutation object of the builder.
func (_u *ClusterSettingUpdate) Mutation() *ClusterSettingMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ClusterSettingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClusterSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ClusterSettingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClusterSettingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ClusterSettingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := clustersetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClusterSettingUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := clustersetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ClusterSetting.key": %w`, err)}
		}
	}
	return nil
}

func (_u *ClusterSettingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clustersetting.Table, clustersetting.Columns, sqlgraph.NewFieldSpec(clustersetting.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(clustersetting.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(clustersetting.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(clustersetting.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clustersetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ClusterSettingUpdateOne is the builder for updating a single ClusterSetting entity.
type ClusterSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClusterSettingMutation
}

// SetKey sets the "key" field.
func (_u *ClusterSettingUpdateOne) SetKey(v string) *ClusterSettingUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *ClusterSettingUpdateOne) SetNillableKey(v *string) *ClusterSettingUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *ClusterSettingUpdateOne) SetValue(v string) *ClusterSettingUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *ClusterSettingUpdateOne) SetNillableValue(v *string) *ClusterSettingUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ClusterSettingUpdateOne) SetUpdatedAt(v time.Time) *ClusterSettingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the ClusterSettingMutation object of the builder.
func (_u *ClusterSettingUpdateOne) Mutation() *ClusterSettingMutation {
	return _u.mutation
}

// Where appends a list predicates to the ClusterSettingUpdate builder.
func (_u *ClusterSettingUpdateOne) Where(ps ...predicate.ClusterSetting) *ClusterSettingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ClusterSettingUpdateOne) Select(field string, fields ...string) *ClusterSettingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ClusterSetting entity.
func (_u *ClusterSettingUpdateOne) Save(ctx context.Context) (*ClusterSetting, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClusterSettingUpdateOne) SaveX(ctx context.Context) *ClusterSetting {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ClusterSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClusterSettingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ClusterSettingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := clustersetting.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClusterSettingUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := clustersetting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "ClusterSetting.key": %w`, err)}
		}
	}
	return nil
}

func (_u *ClusterSettingUpdateOne) sqlSave(ctx context.Context) (_node *ClusterSetting, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clustersetting.Table, clustersetting.Columns, sqlgraph.NewFieldSpec(clustersetting.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ClusterSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, clustersetting.FieldID)
		for _, f := range fields {
			if !clustersetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != clustersetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(clustersetting.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(clustersetting.FieldValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(clustersetting.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &ClusterSetting{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clustersetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
