// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"localshare/internal/store/ent/node"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NodeCreate is the builder for creating a Node entity.
type NodeCreate struct {
	config
	mutation *NodeMutation
	hooks    []Hook
}

// SetNodeID sets the "node_id" field.
func (_c *NodeCreate) SetNodeID(v string) *NodeCreate {
	_c.mutation.SetNodeID(v)
	return _c
}

// SetSSHServer sets the "ssh_server" field.
func (_c *NodeCreate) SetSSHServer(v string) *NodeCreate {
	_c.mutation.SetSSHServer(v)
	return _c
}

// SetNillableSSHServer sets the "ssh_server" field if the given value is not nil.
func (_c *NodeCreate) SetNillableSSHServer(v *string) *NodeCreate {
	if v != nil {
		_c.SetSSHServer(*v)
	}
	return _c
}

// SetPublicBaseURL sets the "public_base_url" field.
func (_c *NodeCreate) SetPublicBaseURL(v string) *NodeCreate {
	_c.mutation.SetPublicBaseURL(v)
	return _c
}

// SetNillablePublicBaseURL sets the "public_base_url" field if the given value is not nil.
func (_c *NodeCreate) SetNillablePublicBaseURL(v *string) *NodeCreate {
	if v != nil {
		_c.SetPublicBaseURL(*v)
	}
	return _c
}

// SetWeight sets the "weight" field.
func (_c *NodeCreate) SetWeight(v int) *NodeCreate {
	_c.mutation.SetWeight(v)
	return _c
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_c *NodeCreate) SetNillableWeight(v *int) *NodeCreate {
	if v != nil {
		_c.SetWeight(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *NodeCreate) SetEnabled(v bool) *NodeCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *NodeCreate) SetNillableEnabled(v *bool) *NodeCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetMaintenance sets the "maintenance" field.
func (_c *NodeCreate) SetMaintenance(v bool) *NodeCreate {
	_c.mutation.SetMaintenance(v)
	return _c
}

// SetNillableMaintenance sets the "maintenance" field if the given value is not nil.
func (_c *NodeCreate) SetNillableMaintenance(v *bool) *NodeCreate {
	if v != nil {
		_c.SetMaintenance(*v)
	}
	return _c
}

// SetMaxTunnels sets the "max_tunnels" field.
func (_c *NodeCreate) SetMaxTunnels(v int) *NodeCreate {
	_c.mutation.SetMaxTunnels(v)
	return _c
}

// SetNillableMaxTunnels sets the "max_tunnels" field if the given value is not nil.
func (_c *NodeCreate) SetNillableMaxTunnels(v *int) *NodeCreate {
	if v != nil {
		_c.SetMaxTunnels(*v)
	}
	return _c
}

// SetCurrentTunnels sets the "current_tunnels" field.
func (_c *NodeCreate) SetCurrentTunnels(v int) *NodeCreate {
	_c.mutation.SetCurrentTunnels(v)
	return _c
}

// SetNillableCurrentTunnels sets the "current_tunnels" field if the given value is not nil.
func (_c *NodeCreate) SetNillableCurrentTunnels(v *int) *NodeCreate {
	if v != nil {
		_c.SetCurrentTunnels(*v)
	}
	return _c
}

// SetMaxActiveConnections sets the "max_active_connections" field.
func (_c *NodeCreate) SetMaxActiveConnections(v int) *NodeCreate {
	_c.mutation.SetMaxActiveConnections(v)
	return _c
}

// SetNillableMaxActiveConnections sets the "max_active_connections" field if the given value is not nil.
func (_c *NodeCreate) SetNillableMaxActiveConnections(v *int) *NodeCreate {
	if v != nil {
		_c.SetMaxActiveConnections(*v)
	}
	return _c
}

// SetActiveConnections sets the "active_connections" field.
func (_c *NodeCreate) SetActiveConnections(v int) *NodeCreate {
	_c.mutation.SetActiveConnections(v)
	return _c
}

// SetNillableActiveConnections sets the "active_connections" field if the given value is not nil.
func (_c *NodeCreate) SetNillableActiveConnections(v *int) *NodeCreate {
	if v != nil {
		_c.SetActiveConnections(*v)
	}
	return _c
}

// SetRegion sets the "region" field.
func (_c *NodeCreate) SetRegion(v string) *NodeCreate {
	_c.mutation.SetRegion(v)
	return _c
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_c *NodeCreate) SetNillableRegion(v *string) *NodeCreate {
	if v != nil {
		_c.SetRegion(*v)
	}
	return _c
}

// SetToken sets the "token" field.
func (_c *NodeCreate) SetToken(v string) *NodeCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_c *NodeCreate) SetNillableToken(v *string) *NodeCreate {
	if v != nil {
		_c.SetToken(*v)
	}
	return _c
}

// SetLastHeartbeat sets the "last_heartbeat" field.
func (_c *NodeCreate) SetLastHeartbeat(v time.Time) *NodeCreate {
	_c.mutation.SetLastHeartbeat(v)
	return _c
}

// SetNillableLastHeartbeat sets the "last_heartbeat" field if the given value is not nil.
func (_c *NodeCreate) SetNillableLastHeartbeat(v *time.Time) *NodeCreate {
	if v != nil {
		_c.SetLastHeartbeat(*v)
	}
	return _c
}

// SetIsLocal sets the "is_local" field.
func (_c *NodeCreate) SetIsLocal(v bool) *NodeCreate {
	_c.mutation.SetIsLocal(v)
	return _c
}

// SetNillableIsLocal sets the "is_local" field if the given value is not nil.
func (_c *NodeCreate) SetNillableIsLocal(v *bool) *NodeCreate {
	if v != nil {
		_c.SetIsLocal(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *NodeCreate) SetCreatedAt(v time.Time) *NodeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *NodeCreate) SetNillableCreatedAt(v *time.Time) *NodeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *NodeCreate) SetUpdatedAt(v time.Time) *NodeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *NodeCreate) SetNillableUpdatedAt(v *time.Time) *NodeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the NodeMutation object of the builder.
func (_c *NodeCreate) Mutation() *NodeMutation {
	return _c.mutation
}

// Save creates the Node in the database.
func (_c *NodeCreate) Save(ctx context.Context) (*Node, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *NodeCreate) SaveX(ctx context.Context) *Node {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *NodeCreate) defaults() {
	if _, ok := _c.mutation.SSHServer(); !ok {
		v := node.DefaultSSHServer
		_c.mutation.SetSSHServer(v)
	}
	if _, ok := _c.mutation.PublicBaseURL(); !ok {
		v := node.DefaultPublicBaseURL
		_c.mutation.SetPublicBaseURL(v)
	}
	if _, ok := _c.mutation.Weight(); !ok {
		v := node.DefaultWeight
		_c.mutation.SetWeight(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := node.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Maintenance(); !ok {
		v := node.DefaultMaintenance
		_c.mutation.SetMaintenance(v)
	}
	if _, ok := _c.mutation.MaxTunnels(); !ok {
		v := node.DefaultMaxTunnels
		_c.mutation.SetMaxTunnels(v)
	}
	if _, ok := _c.mutation.CurrentTunnels(); !ok {
		v := node.DefaultCurrentTunnels
		_c.mutation.SetCurrentTunnels(v)
	}
	if _, ok := _c.mutation.MaxActiveConnections(); !ok {
		v := node.DefaultMaxActiveConnections
		_c.mutation.SetMaxActiveConnections(v)
	}
	if _, ok := _c.mutation.ActiveConnections(); !ok {
		v := node.DefaultActiveConnections
		_c.mutation.SetActiveConnections(v)
	}
	if _, ok := _c.mutation.Region(); !ok {
		v := node.DefaultRegion
		_c.mutation.SetRegion(v)
	}
	if _, ok := _c.mutation.Token(); !ok {
		v := node.DefaultToken
		_c.mutation.SetToken(v)
	}
	if _, ok := _c.mutation.LastHeartbeat(); !ok {
		v := node.DefaultLastHeartbeat()
		_c.mutation.SetLastHeartbeat(v)
	}
	if _, ok := _c.mutation.IsLocal(); !ok {
		v := node.DefaultIsLocal
		_c.mutation.SetIsLocal(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := node.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := node.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *NodeCreate) check() error {
	if _, ok := _c.mutation.NodeID(); !ok {
		return &ValidationError{Name: "node_id", err: errors.New(`ent: missing required field "Node.node_id"`)}
	}
	if v, ok := _c.mutation.NodeID(); ok {
		if err := node.NodeIDValidator(v); err != nil {
			return &ValidationError{Name: "node_id", err: fmt.Errorf(`ent: validator failed for field "Node.node_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SSHServer(); !ok {
		return &ValidationError{Name: "ssh_server", err: errors.New(`ent: missing required field "Node.ssh_server"`)}
	}
	if _, ok := _c.mutation.PublicBaseURL(); !ok {
		return &ValidationError{Name: "public_base_url", err: errors.New(`ent: missing required field "Node.public_base_url"`)}
	}
	if _, ok := _c.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`ent: missing required field "Node.weight"`)}
	}
	if v, ok := _c.mutation.Weight(); ok {
		if err := node.WeightValidator(v); err != nil {
			return &ValidationError{Name: "weight", err: fmt.Errorf(`ent: validator failed for field "Node.weight": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Node.enabled"`)}
	}
	if _, ok := _c.mutation.Maintenance(); !ok {
		return &ValidationError{Name: "maintenance", err: errors.New(`ent: missing required field "Node.maintenance"`)}
	}
	if _, ok := _c.mutation.MaxTunnels(); !ok {
		return &ValidationError{Name: "max_tunnels", err: errors.New(`ent: missing required field "Node.max_tunnels"`)}
	}
	if v, ok := _c.mutation.MaxTunnels(); ok {
		if err := node.MaxTunnelsValidator(v); err != nil {
			return &ValidationError{Name: "max_tunnels", err: fmt.Errorf(`ent: validator failed for field "Node.max_tunnels": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CurrentTunnels(); !ok {
		return &ValidationError{Name: "current_tunnels", err: errors.New(`ent: missing required field "Node.current_tunnels"`)}
	}
	if v, ok := _c.mutation.CurrentTunnels(); ok {
		if err := node.CurrentTunnelsValidator(v); err != nil {
			return &ValidationError{Name: "current_tunnels", err: fmt.Errorf(`ent: validator failed for field "Node.current_tunnels": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MaxActiveConnections(); !ok {
		return &ValidationError{Name: "max_active_connections", err: errors.New(`ent: missing required field "Node.max_active_connections"`)}
	}
	if v, ok := _c.mutation.MaxActiveConnections(); ok {
		if err := node.MaxActiveConnectionsValidator(v); err != nil {
			return &ValidationError{Name: "max_active_connections", err: fmt.Errorf(`ent: validator failed for field "Node.max_active_connections": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActiveConnections(); !ok {
		return &ValidationError{Name: "active_connections", err: errors.New(`ent: missing required field "Node.active_connections"`)}
	}
	if v, ok := _c.mutation.ActiveConnections(); ok {
		if err := node.ActiveConnectionsValidator(v); err != nil {
			return &ValidationError{Name: "active_connections", err: fmt.Errorf(`ent: validator failed for field "Node.active_connections": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Region(); !ok {
		return &ValidationError{Name: "region", err: errors.New(`ent: missing required field "Node.region"`)}
	}
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "Node.token"`)}
	}
	if _, ok := _c.mutation.LastHeartbeat(); !ok {
		return &ValidationError{Name: "last_heartbeat", err: errors.New(`ent: missing required field "Node.last_heartbeat"`)}
	}
	if _, ok := _c.mutation.IsLocal(); !ok {
		return &ValidationError{Name: "is_local", err: errors.New(`ent: missing required field "Node.is_local"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Node.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Node.updated_at"`)}
	}
	return nil
}

func (_c *NodeCreate) sqlSave(ctx context.Context) (*Node, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *NodeCreate) createSpec() (*Node, *sqlgraph.CreateSpec) {
	var (
		_node = &Node{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(node.Table, sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.NodeID(); ok {
		_spec.SetField(node.FieldNodeID, field.TypeString, value)
		_node.NodeID = value
	}
	if value, ok := _c.mutation.SSHServer(); ok {
		_spec.SetField(node.FieldSSHServer, field.TypeString, value)
		_node.SSHServer = value
	}
	if value, ok := _c.mutation.PublicBaseURL(); ok {
		_spec.SetField(node.FieldPublicBaseURL, field.TypeString, value)
		_node.PublicBaseURL = value
	}
	if value, ok := _c.mutation.Weight(); ok {
		_spec.SetField(node.FieldWeight, field.TypeInt, value)
		_node.Weight = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(node.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Maintenance(); ok {
		_spec.SetField(node.FieldMaintenance, field.TypeBool, value)
		_node.Maintenance = value
	}
	if value, ok := _c.mutation.MaxTunnels(); ok {
		_spec.SetField(node.FieldMaxTunnels, field.TypeInt, value)
		_node.MaxTunnels = value
	}
	if value, ok := _c.mutation.CurrentTunnels(); ok {
		_spec.SetField(node.FieldCurrentTunnels, field.TypeInt, value)
		_node.CurrentTunnels = value
	}
	if value, ok := _c.mutation.MaxActiveConnections(); ok {
		_spec.SetField(node.FieldMaxActiveConnections, field.TypeInt, value)
		_node.MaxActiveConnections = value
	}
	if value, ok := _c.mutation.ActiveConnections(); ok {
		_spec.SetField(node.FieldActiveConnections, field.TypeInt, value)
		_node.ActiveConnections = value
	}
	if value, ok := _c.mutation.Region(); ok {
		_spec.SetField(node.FieldRegion, field.TypeString, value)
		_node.Region = value
	}
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(node.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.LastHeartbeat(); ok {
		_spec.SetField(node.FieldLastHeartbeat, field.TypeTime, value)
		_node.LastHeartbeat = value
	}
	if value, ok := _c.mutation.IsLocal(); ok {
		_spec.SetField(node.FieldIsLocal, field.TypeBool, value)
		_node.IsLocal = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(node.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// NodeCreateBulk is the builder for creating many Node entities in bulk.
type NodeCreateBulk struct {
	config
	err      error
	builders []*NodeCreate
}

// Save creates the Node entities in the database.
func (_c *NodeCreateBulk) Save(ctx context.Context) ([]*Node, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Node, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NodeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *NodeCreateBulk) SaveX(ctx context.Context) []*Node {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *NodeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *NodeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
