// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"localshare/internal/store/ent/node"
	"localshare/internal/store/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// NodeUpdate is the builder for updating Node entities.
type NodeUpdate struct {
	config
	hooks    []Hook
	mutation *NodeMutation
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdate) Where(ps ...predicate.Node) *NodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *NodeUpdate) SetNodeID(v string) *NodeUpdate {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableNodeID(v *string) *NodeUpdate {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// SetSSHServer sets the "ssh_server" field.
func (_u *NodeUpdate) SetSSHServer(v string) *NodeUpdate {
	_u.mutation.SetSSHServer(v)
	return _u
}

// SetNillableSSHServer sets the "ssh_server" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableSSHServer(v *string) *NodeUpdate {
	if v != nil {
		_u.SetSSHServer(*v)
	}
	return _u
}

// SetPublicBaseURL sets the "public_base_url" field.
func (_u *NodeUpdate) SetPublicBaseURL(v string) *NodeUpdate {
	_u.mutation.SetPublicBaseURL(v)
	return _u
}

// SetNillablePublicBaseURL sets the "public_base_url" field if the given value is not nil.
func (_u *NodeUpdate) SetNillablePublicBaseURL(v *string) *NodeUpdate {
	if v != nil {
		_u.SetPublicBaseURL(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *NodeUpdate) SetWeight(v int) *NodeUpdate {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableWeight(v *int) *NodeUpdate {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *NodeUpdate) AddWeight(v int) *NodeUpdate {
	_u.mutation.AddWeight(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NodeUpdate) SetEnabled(v bool) *NodeUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableEnabled(v *bool) *NodeUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetMaintenance sets the "maintenance" field.
func (_u *NodeUpdate) SetMaintenance(v bool) *NodeUpdate {
	_u.mutation.SetMaintenance(v)
	return _u
}

// SetNillableMaintenance sets the "maintenance" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableMaintenance(v *bool) *NodeUpdate {
	if v != nil {
		_u.SetMaintenance(*v)
	}
	return _u
}

// SetMaxTunnels sets the "max_tunnels" field.
func (_u *NodeUpdate) SetMaxTunnels(v int) *NodeUpdate {
	_u.mutation.ResetMaxTunnels()
	_u.mutation.SetMaxTunnels(v)
	return _u
}

// SetNillableMaxTunnels sets the "max_tunnels" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableMaxTunnels(v *int) *NodeUpdate {
	if v != nil {
		_u.SetMaxTunnels(*v)
	}
	return _u
}

// AddMaxTunnels adds value to the "max_tunnels" field.
func (_u *NodeUpdate) AddMaxTunnels(v int) *NodeUpdate {
	_u.mutation.AddMaxTunnels(v)
	return _u
}

// SetCurrentTunnels sets the "current_tunnels" field.
func (_u *NodeUpdate) SetCurrentTunnels(v int) *NodeUpdate {
	_u.mutation.ResetCurrentTunnels()
	_u.mutation.SetCurrentTunnels(v)
	return _u
}

// SetNillableCurrentTunnels sets the "current_tunnels" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableCurrentTunnels(v *int) *NodeUpdate {
	if v != nil {
		_u.SetCurrentTunnels(*v)
	}
	return _u
}

// AddCurrentTunnels adds value to the "current_tunnels" field.
func (_u *NodeUpdate) AddCurrentTunnels(v int) *NodeUpdate {
	_u.mutation.AddCurrentTunnels(v)
	return _u
}

// SetMaxActiveConnections sets the "max_active_connections" field.
func (_u *NodeUpdate) SetMaxActiveConnections(v int) *NodeUpdate {
	_u.mutation.ResetMaxActiveConnections()
	_u.mutation.SetMaxActiveConnections(v)
	return _u
}

// SetNillableMaxActiveConnections sets the "max_active_connections" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableMaxActiveConnections(v *int) *NodeUpdate {
	if v != nil {
		_u.SetMaxActiveConnections(*v)
	}
	return _u
}

// AddMaxActiveConnections adds value to the "max_active_connections" field.
func (_u *NodeUpdate) AddMaxActiveConnections(v int) *NodeUpdate {
	_u.mutation.AddMaxActiveConnections(v)
	return _u
}

// SetActiveConnections sets the "active_connections" field.
func (_u *NodeUpdate) SetActiveConnections(v int) *NodeUpdate {
	_u.mutation.ResetActiveConnections()
	_u.mutation.SetActiveConnections(v)
	return _u
}

// SetNillableActiveConnections sets the "active_connections" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableActiveConnections(v *int) *NodeUpdate {
	if v != nil {
		_u.SetActiveConnections(*v)
	}
	return _u
}

// AddActiveConnections adds value to the "active_connections" field.
func (_u *NodeUpdate) AddActiveConnections(v int) *NodeUpdate {
	_u.mutation.AddActiveConnections(v)
	return _u
}

// SetRegion sets the "region" field.
func (_u *NodeUpdate) SetRegion(v string) *NodeUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableRegion(v *string) *NodeUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *NodeUpdate) SetToken(v string) *NodeUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableToken(v *string) *NodeUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetLastHeartbeat sets the "last_heartbeat" field.
func (_u *NodeUpdate) SetLastHeartbeat(v time.Time) *NodeUpdate {
	_u.mutation.SetLastHeartbeat(v)
	return _u
}

// SetNillableLastHeartbeat sets the "last_heartbeat" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableLastHeartbeat(v *time.Time) *NodeUpdate {
	if v != nil {
		_u.SetLastHeartbeat(*v)
	}
	return _u
}

// SetIsLocal sets the "is_local" field.
func (_u *NodeUpdate) SetIsLocal(v bool) *NodeUpdate {
	_u.mutation.SetIsLocal(v)
	return _u
}

// SetNillableIsLocal sets the "is_local" field if the given value is not nil.
func (_u *NodeUpdate) SetNillableIsLocal(v *bool) *NodeUpdate {
	if v != nil {
		_u.SetIsLocal(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeUpdate) SetUpdatedAt(v time.Time) *NodeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdate) Mutation() *NodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *NodeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *NodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := node.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeUpdate) check() error {
	if v, ok := _u.mutation.NodeID(); ok {
		if err := node.NodeIDValidator(v); err != nil {
			return &ValidationError{Name: "node_id", err: fmt.Errorf(`ent: validator failed for field "Node.node_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Weight(); ok {
		if err := node.WeightValidator(v); err != nil {
			return &ValidationError{Name: "weight", err: fmt.Errorf(`ent: validator failed for field "Node.weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxTunnels(); ok {
		if err := node.MaxTunnelsValidator(v); err != nil {
			return &ValidationError{Name: "max_tunnels", err: fmt.Errorf(`ent: validator failed for field "Node.max_tunnels": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentTunnels(); ok {
		if err := node.CurrentTunnelsValidator(v); err != nil {
			return &ValidationError{Name: "current_tunnels", err: fmt.Errorf(`ent: validator failed for field "Node.current_tunnels": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxActiveConnections(); ok {
		if err := node.MaxActiveConnectionsValidator(v); err != nil {
			return &ValidationError{Name: "max_active_connections", err: fmt.Errorf(`ent: validator failed for field "Node.max_active_connections": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActiveConnections(); ok {
		if err := node.ActiveConnectionsValidator(v); err != nil {
			return &ValidationError{Name: "active_connections", err: fmt.Errorf(`ent: validator failed for field "Node.active_connections": %w`, err)}
		}
	}
	return nil
}

func (_u *NodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(node.FieldNodeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SSHServer(); ok {
		_spec.SetField(node.FieldSSHServer, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicBaseURL(); ok {
		_spec.SetField(node.FieldPublicBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(node.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(node.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(node.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Maintenance(); ok {
		_spec.SetField(node.FieldMaintenance, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaxTunnels(); ok {
		_spec.SetField(node.FieldMaxTunnels, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTunnels(); ok {
		_spec.AddField(node.FieldMaxTunnels, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CurrentTunnels(); ok {
		_spec.SetField(node.FieldCurrentTunnels, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentTunnels(); ok {
		_spec.AddField(node.FieldCurrentTunnels, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxActiveConnections(); ok {
		_spec.SetField(node.FieldMaxActiveConnections, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxActiveConnections(); ok {
		_spec.AddField(node.FieldMaxActiveConnections, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActiveConnections(); ok {
		_spec.SetField(node.FieldActiveConnections, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActiveConnections(); ok {
		_spec.AddField(node.FieldActiveConnections, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(node.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(node.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastHeartbeat(); ok {
		_spec.SetField(node.FieldLastHeartbeat, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsLocal(); ok {
		_spec.SetField(node.FieldIsLocal, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// NodeUpdateOne is the builder for updating a single Node entity.
type NodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NodeMutation
}

// SetNodeID sets the "node_id" field.
func (_u *NodeUpdateOne) SetNodeID(v string) *NodeUpdateOne {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableNodeID(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// SetSSHServer sets the "ssh_server" field.
func (_u *NodeUpdateOne) SetSSHServer(v string) *NodeUpdateOne {
	_u.mutation.SetSSHServer(v)
	return _u
}

// SetNillableSSHServer sets the "ssh_server" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableSSHServer(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetSSHServer(*v)
	}
	return _u
}

// SetPublicBaseURL sets the "public_base_url" field.
func (_u *NodeUpdateOne) SetPublicBaseURL(v string) *NodeUpdateOne {
	_u.mutation.SetPublicBaseURL(v)
	return _u
}

// SetNillablePublicBaseURL sets the "public_base_url" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillablePublicBaseURL(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetPublicBaseURL(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *NodeUpdateOne) SetWeight(v int) *NodeUpdateOne {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableWeight(v *int) *NodeUpdateOne {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *NodeUpdateOne) AddWeight(v int) *NodeUpdateOne {
	_u.mutation.AddWeight(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *NodeUpdateOne) SetEnabled(v bool) *NodeUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableEnabled(v *bool) *NodeUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetMaintenance sets the "maintenance" field.
func (_u *NodeUpdateOne) SetMaintenance(v bool) *NodeUpdateOne {
	_u.mutation.SetMaintenance(v)
	return _u
}

// SetNillableMaintenance sets the "maintenance" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableMaintenance(v *bool) *NodeUpdateOne {
	if v != nil {
		_u.SetMaintenance(*v)
	}
	return _u
}

// SetMaxTunnels sets the "max_tunnels" field.
func (_u *NodeUpdateOne) SetMaxTunnels(v int) *NodeUpdateOne {
	_u.mutation.ResetMaxTunnels()
	_u.mutation.SetMaxTunnels(v)
	return _u
}

// SetNillableMaxTunnels sets the "max_tunnels" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableMaxTunnels(v *int) *NodeUpdateOne {
	if v != nil {
		_u.SetMaxTunnels(*v)
	}
	return _u
}

// AddMaxTunnels adds value to the "max_tunnels" field.
func (_u *NodeUpdateOne) AddMaxTunnels(v int) *NodeUpdateOne {
	_u.mutation.AddMaxTunnels(v)
	return _u
}

// SetCurrentTunnels sets the "current_tunnels" field.
func (_u *NodeUpdateOne) SetCurrentTunnels(v int) *NodeUpdateOne {
	_u.mutation.ResetCurrentTunnels()
	_u.mutation.SetCurrentTunnels(v)
	return _u
}

// SetNillableCurrentTunnels sets the "current_tunnels" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableCurrentTunnels(v *int) *NodeUpdateOne {
	if v != nil {
		_u.SetCurrentTunnels(*v)
	}
	return _u
}

// AddCurrentTunnels adds value to the "current_tunnels" field.
func (_u *NodeUpdateOne) AddCurrentTunnels(v int) *NodeUpdateOne {
	_u.mutation.AddCurrentTunnels(v)
	return _u
}

// SetMaxActiveConnections sets the "max_active_connections" field.
func (_u *NodeUpdateOne) SetMaxActiveConnections(v int) *NodeUpdateOne {
	_u.mutation.ResetMaxActiveConnections()
	_u.mutation.SetMaxActiveConnections(v)
	return _u
}

// SetNillableMaxActiveConnections sets the "max_active_connections" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableMaxActiveConnections(v *int) *NodeUpdateOne {
	if v != nil {
		_u.SetMaxActiveConnections(*v)
	}
	return _u
}

// AddMaxActiveConnections adds value to the "max_active_connections" field.
func (_u *NodeUpdateOne) AddMaxActiveConnections(v int) *NodeUpdateOne {
	_u.mutation.AddMaxActiveConnections(v)
	return _u
}

// SetActiveConnections sets the "active_connections" field.
func (_u *NodeUpdateOne) SetActiveConnections(v int) *NodeUpdateOne {
	_u.mutation.ResetActiveConnections()
	_u.mutation.SetActiveConnections(v)
	return _u
}

// SetNillableActiveConnections sets the "active_connections" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableActiveConnections(v *int) *NodeUpdateOne {
	if v != nil {
		_u.SetActiveConnections(*v)
	}
	return _u
}

// AddActiveConnections adds value to the "active_connections" field.
func (_u *NodeUpdateOne) AddActiveConnections(v int) *NodeUpdateOne {
	_u.mutation.AddActiveConnections(v)
	return _u
}

// SetRegion sets the "region" field.
func (_u *NodeUpdateOne) SetRegion(v string) *NodeUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableRegion(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// SetToken sets the "token" field.
func (_u *NodeUpdateOne) SetToken(v string) *NodeUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableToken(v *string) *NodeUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetLastHeartbeat sets the "last_heartbeat" field.
func (_u *NodeUpdateOne) SetLastHeartbeat(v time.Time) *NodeUpdateOne {
	_u.mutation.SetLastHeartbeat(v)
	return _u
}

// SetNillableLastHeartbeat sets the "last_heartbeat" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableLastHeartbeat(v *time.Time) *NodeUpdateOne {
	if v != nil {
		_u.SetLastHeartbeat(*v)
	}
	return _u
}

// SetIsLocal sets the "is_local" field.
func (_u *NodeUpdateOne) SetIsLocal(v bool) *NodeUpdateOne {
	_u.mutation.SetIsLocal(v)
	return _u
}

// SetNillableIsLocal sets the "is_local" field if the given value is not nil.
func (_u *NodeUpdateOne) SetNillableIsLocal(v *bool) *NodeUpdateOne {
	if v != nil {
		_u.SetIsLocal(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *NodeUpdateOne) SetUpdatedAt(v time.Time) *NodeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the NodeMutation object of the builder.
func (_u *NodeUpdateOne) Mutation() *NodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the NodeUpdate builder.
func (_u *NodeUpdateOne) Where(ps ...predicate.Node) *NodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *NodeUpdateOne) Select(field string, fields ...string) *NodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Node entity.
func (_u *NodeUpdateOne) Save(ctx context.Context) (*Node, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *NodeUpdateOne) SaveX(ctx context.Context) *Node {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *NodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *NodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *NodeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := node.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *NodeUpdateOne) check() error {
	if v, ok := _u.mutation.NodeID(); ok {
		if err := node.NodeIDValidator(v); err != nil {
			return &ValidationError{Name: "node_id", err: fmt.Errorf(`ent: validator failed for field "Node.node_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Weight(); ok {
		if err := node.WeightValidator(v); err != nil {
			return &ValidationError{Name: "weight", err: fmt.Errorf(`ent: validator failed for field "Node.weight": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxTunnels(); ok {
		if err := node.MaxTunnelsValidator(v); err != nil {
			return &ValidationError{Name: "max_tunnels", err: fmt.Errorf(`ent: validator failed for field "Node.max_tunnels": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CurrentTunnels(); ok {
		if err := node.CurrentTunnelsValidator(v); err != nil {
			return &ValidationError{Name: "current_tunnels", err: fmt.Errorf(`ent: validator failed for field "Node.current_tunnels": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxActiveConnections(); ok {
		if err := node.MaxActiveConnectionsValidator(v); err != nil {
			return &ValidationError{Name: "max_active_connections", err: fmt.Errorf(`ent: validator failed for field "Node.max_active_connections": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ActiveConnections(); ok {
		if err := node.ActiveConnectionsValidator(v); err != nil {
			return &ValidationError{Name: "active_connections", err: fmt.Errorf(`ent: validator failed for field "Node.active_connections": %w`, err)}
		}
	}
	return nil
}

func (_u *NodeUpdateOne) sqlSave(ctx context.Context) (_node *Node, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(node.Table, node.Columns, sqlgraph.NewFieldSpec(node.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Node.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, node.FieldID)
		for _, f := range fields {
			if !node.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != node.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(node.FieldNodeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.SSHServer(); ok {
		_spec.SetField(node.FieldSSHServer, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicBaseURL(); ok {
		_spec.SetField(node.FieldPublicBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(node.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(node.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(node.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Maintenance(); ok {
		_spec.SetField(node.FieldMaintenance, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaxTunnels(); ok {
		_spec.SetField(node.FieldMaxTunnels, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxTunnels(); ok {
		_spec.AddField(node.FieldMaxTunnels, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CurrentTunnels(); ok {
		_spec.SetField(node.FieldCurrentTunnels, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentTunnels(); ok {
		_spec.AddField(node.FieldCurrentTunnels, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxActiveConnections(); ok {
		_spec.SetField(node.FieldMaxActiveConnections, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxActiveConnections(); ok {
		_spec.AddField(node.FieldMaxActiveConnections, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ActiveConnections(); ok {
		_spec.SetField(node.FieldActiveConnections, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedActiveConnections(); ok {
		_spec.AddField(node.FieldActiveConnections, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(node.FieldRegion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(node.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastHeartbeat(); ok {
		_spec.SetField(node.FieldLastHeartbeat, field.TypeTime, value)
	}
	if value, ok := _u.mutation.IsLocal(); ok {
		_spec.SetField(node.FieldIsLocal, field.TypeBool, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(node.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Node{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{node.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
