// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"localshare/internal/store/ent/node"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Node is the model entity for the Node schema.
type Node struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// NodeID holds the value of the "node_id" field.
	NodeID string `json:"node_id,omitempty"`
	// SSHServer holds the value of the "ssh_server" field.
	SSHServer string `json:"ssh_server,omitempty"`
	// PublicBaseURL holds the value of the "public_base_url" field.
	PublicBaseURL string `json:"public_base_url,omitempty"`
	// Weight holds the value of the "weight" field.
	Weight int `json:"weight,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Maintenance holds the value of the "maintenance" field.
	Maintenance bool `json:"maintenance,omitempty"`
	// MaxTunnels holds the value of the "max_tunnels" field.
	MaxTunnels int `json:"max_tunnels,omitempty"`
	// CurrentTunnels holds the value of the "current_tunnels" field.
	CurrentTunnels int `json:"current_tunnels,omitempty"`
	// MaxActiveConnections holds the value of the "max_active_connections" field.
	MaxActiveConnections int `json:"max_active_connections,omitempty"`
	// ActiveConnections holds the value of the "active_connections" field.
	ActiveConnections int `json:"active_connections,omitempty"`
	// Region holds the value of the "region" field.
	Region string `json:"region,omitempty"`
	// Token holds the value of the "token" field.
	Token string `json:"token,omitempty"`
	// LastHeartbeat holds the value of the "last_heartbeat" field.
	LastHeartbeat time.Time `json:"last_heartbeat,omitempty"`
	// IsLocal holds the value of the "is_local" field.
	IsLocal bool `json:"is_local,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Node) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case node.FieldEnabled, node.FieldMaintenance, node.FieldIsLocal:
			values[i] = new(sql.NullBool)
		case node.FieldID, node.FieldWeight, node.FieldMaxTunnels, node.FieldCurrentTunnels, node.FieldMaxActiveConnections, node.FieldActiveConnections:
			values[i] = new(sql.NullInt64)
		case node.FieldNodeID, node.FieldSSHServer, node.FieldPublicBaseURL, node.FieldRegion, node.FieldToken:
			values[i] = new(sql.NullString)
		case node.FieldLastHeartbeat, node.FieldCreatedAt, node.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Node fields.
func (_m *Node) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case node.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case node.FieldNodeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field node_id", values[i])
			} else if value.Valid {
				_m.NodeID = value.String
			}
		case node.FieldSSHServer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ssh_server", values[i])
			} else if value.Valid {
				_m.SSHServer = value.String
			}
		case node.FieldPublicBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_base_url", values[i])
			} else if value.Valid {
				_m.PublicBaseURL = value.String
			}
		case node.FieldWeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weight", values[i])
			} else if value.Valid {
				_m.Weight = int(value.Int64)
			}
		case node.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case node.FieldMaintenance:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field maintenance", values[i])
			} else if value.Valid {
				_m.Maintenance = value.Bool
			}
		case node.FieldMaxTunnels:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_tunnels", values[i])
			} else if value.Valid {
				_m.MaxTunnels = int(value.Int64)
			}
		case node.FieldCurrentTunnels:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field current_tunnels", values[i])
			} else if value.Valid {
				_m.CurrentTunnels = int(value.Int64)
			}
		case node.FieldMaxActiveConnections:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_active_connections", values[i])
			} else if value.Valid {
				_m.MaxActiveConnections = int(value.Int64)
			}
		case node.FieldActiveConnections:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field active_connections", values[i])
			} else if value.Valid {
				_m.ActiveConnections = int(value.Int64)
			}
		case node.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = value.String
			}
		case node.FieldToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field token", values[i])
			} else if value.Valid {
				_m.Token = value.String
			}
		case node.FieldLastHeartbeat:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_heartbeat", values[i])
			} else if value.Valid {
				_m.LastHeartbeat = value.Time
			}
		case node.FieldIsLocal:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_local", values[i])
			} else if value.Valid {
				_m.IsLocal = value.Bool
			}
		case node.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case node.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Node.
// This includes values selected through modifiers, order, etc.
func (_m *Node) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Node.
// Note that you need to call Node.Unwrap() before calling this method if this Node
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Node) Update() *NodeUpdateOne {
	return NewNodeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Node entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Node) Unwrap() *Node {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Node is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Node) String() string {
	var builder strings.Builder
	builder.WriteString("Node(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("node_id=")
	builder.WriteString(_m.NodeID)
	builder.WriteString(", ")
	builder.WriteString("ssh_server=")
	builder.WriteString(_m.SSHServer)
	builder.WriteString(", ")
	builder.WriteString("public_base_url=")
	builder.WriteString(_m.PublicBaseURL)
	builder.WriteString(", ")
	builder.WriteString("weight=")
	builder.WriteString(fmt.Sprintf("%v", _m.Weight))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("maintenance=")
	builder.WriteString(fmt.Sprintf("%v", _m.Maintenance))
	builder.WriteString(", ")
	builder.WriteString("max_tunnels=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxTunnels))
	builder.WriteString(", ")
	builder.WriteString("current_tunnels=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrentTunnels))
	builder.WriteString(", ")
	builder.WriteString("max_active_connections=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxActiveConnections))
	builder.WriteString(", ")
	builder.WriteString("active_connections=")
	builder.WriteString(fmt.Sprintf("%v", _m.ActiveConnections))
	builder.WriteString(", ")
	builder.WriteString("region=")
	builder.WriteString(_m.Region)
	builder.WriteString(", ")
	builder.WriteString("token=")
	builder.WriteString(_m.Token)
	builder.WriteString(", ")
	builder.WriteString("last_heartbeat=")
	builder.WriteString(_m.LastHeartbeat.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("is_local=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsLocal))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Nodes is a parsable slice of Node.
type Nodes []*Node
