// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"localshare/internal/store/ent/route"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RouteCreate is the builder for creating a Route entity.
type RouteCreate struct {
	config
	mutation *RouteMutation
	hooks    []Hook
}

// SetToken sets the "token" field.
func (_c *RouteCreate) SetToken(v string) *RouteCreate {
	_c.mutation.SetToken(v)
	return _c
}

// SetNodeID sets the "node_id" field.
func (_c *RouteCreate) SetNodeID(v string) *RouteCreate {
	_c.mutation.SetNodeID(v)
	return _c
}

// SetTargetURL sets the "target_url" field.
func (_c *RouteCreate) SetTargetURL(v string) *RouteCreate {
	_c.mutation.SetTargetURL(v)
	return _c
}

// SetPublicURL sets the "public_url" field.
func (_c *RouteCreate) SetPublicURL(v string) *RouteCreate {
	_c.mutation.SetPublicURL(v)
	return _c
}

// SetPeerID sets the "peer_id" field.
func (_c *RouteCreate) SetPeerID(v string) *RouteCreate {
	_c.mutation.SetPeerID(v)
	return _c
}

// SetNillablePeerID sets the "peer_id" field if the given value is not nil.
func (_c *RouteCreate) SetNillablePeerID(v *string) *RouteCreate {
	if v != nil {
		_c.SetPeerID(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *RouteCreate) SetStatus(v string) *RouteCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RouteCreate) SetNillableStatus(v *string) *RouteCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RouteCreate) SetCreatedAt(v time.Time) *RouteCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RouteCreate) SetNillableCreatedAt(v *time.Time) *RouteCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RouteCreate) SetUpdatedAt(v time.Time) *RouteCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RouteCreate) SetNillableUpdatedAt(v *time.Time) *RouteCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *RouteCreate) SetExpiresAt(v time.Time) *RouteCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// Mutation returns the RouteMutation object of the builder.
func (_c *RouteCreate) Mutation() *RouteMutation {
	return _c.mutation
}

// Save creates the Route in the database.
func (_c *RouteCreate) Save(ctx context.Context) (*Route, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RouteCreate) SaveX(ctx context.Context) *Route {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RouteCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RouteCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RouteCreate) defaults() {
	if _, ok := _c.mutation.PeerID(); !ok {
		v := route.DefaultPeerID
		_c.mutation.SetPeerID(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := route.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := route.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := route.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RouteCreate) check() error {
	if _, ok := _c.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "Route.token"`)}
	}
	if v, ok := _c.mutation.Token(); ok {
		if err := route.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Route.token": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NodeID(); !ok {
		return &ValidationError{Name: "node_id", err: errors.New(`ent: missing required field "Route.node_id"`)}
	}
	if v, ok := _c.mutation.NodeID(); ok {
		if err := route.NodeIDValidator(v); err != nil {
			return &ValidationError{Name: "node_id", err: fmt.Errorf(`ent: validator failed for field "Route.node_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TargetURL(); !ok {
		return &ValidationError{Name: "target_url", err: errors.New(`ent: missing required field "Route.target_url"`)}
	}
	if v, ok := _c.mutation.TargetURL(); ok {
		if err := route.TargetURLValidator(v); err != nil {
			return &ValidationError{Name: "target_url", err: fmt.Errorf(`ent: validator failed for field "Route.target_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PublicURL(); !ok {
		return &ValidationError{Name: "public_url", err: errors.New(`ent: missing required field "Route.public_url"`)}
	}
	if v, ok := _c.mutation.PublicURL(); ok {
		if err := route.PublicURLValidator(v); err != nil {
			return &ValidationError{Name: "public_url", err: fmt.Errorf(`ent: validator failed for field "Route.public_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PeerID(); !ok {
		return &ValidationError{Name: "peer_id", err: errors.New(`ent: missing required field "Route.peer_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Route.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Route.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Route.updated_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "Route.expires_at"`)}
	}
	return nil
}

func (_c *RouteCreate) sqlSave(ctx context.Context) (*Route, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RouteCreate) createSpec() (*Route, *sqlgraph.CreateSpec) {
	var (
		_node = &Route{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(route.Table, sqlgraph.NewFieldSpec(route.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Token(); ok {
		_spec.SetField(route.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	if value, ok := _c.mutation.NodeID(); ok {
		_spec.SetField(route.FieldNodeID, field.TypeString, value)
		_node.NodeID = value
	}
	if value, ok := _c.mutation.TargetURL(); ok {
		_spec.SetField(route.FieldTargetURL, field.TypeString, value)
		_node.TargetURL = value
	}
	if value, ok := _c.mutation.PublicURL(); ok {
		_spec.SetField(route.FieldPublicURL, field.TypeString, value)
		_node.PublicURL = value
	}
	if value, ok := _c.mutation.PeerID(); ok {
		_spec.SetField(route.FieldPeerID, field.TypeString, value)
		_node.PeerID = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(route.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(route.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(route.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(route.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	return _node, _spec
}

// RouteCreateBulk is the builder for creating many Route entities in bulk.
type RouteCreateBulk struct {
	config
	err      error
	builders []*RouteCreate
}

// Save creates the Route entities in the database.
func (_c *RouteCreateBulk) Save(ctx context.Context) ([]*Route, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Route, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RouteMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RouteCreateBulk) SaveX(ctx context.Context) []*Route {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RouteCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RouteCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
