// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"localshare/internal/store/ent/predicate"
	"localshare/internal/store/ent/route"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// RouteUpdate is the builder for updating Route entities.
type RouteUpdate struct {
	config
	hooks    []Hook
	mutation *RouteMutation
}

// Where appends a list predicates to the RouteUpdate builder.
func (_u *RouteUpdate) Where(ps ...predicate.Route) *RouteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetToken sets the "token" field.
func (_u *RouteUpdate) SetToken(v string) *RouteUpdate {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *RouteUpdate) SetNillableToken(v *string) *RouteUpdate {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *RouteUpdate) SetNodeID(v string) *RouteUpdate {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *RouteUpdate) SetNillableNodeID(v *string) *RouteUpdate {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// SetTargetURL sets the "target_url" field.
func (_u *RouteUpdate) SetTargetURL(v string) *RouteUpdate {
	_u.mutation.SetTargetURL(v)
	return _u
}

// SetNillableTargetURL sets the "target_url" field if the given value is not nil.
func (_u *RouteUpdate) SetNillableTargetURL(v *string) *RouteUpdate {
	if v != nil {
		_u.SetTargetURL(*v)
	}
	return _u
}

// SetPublicURL sets the "public_url" field.
func (_u *RouteUpdate) SetPublicURL(v string) *RouteUpdate {
	_u.mutation.SetPublicURL(v)
	return _u
}

// SetNillablePublicURL sets the "public_url" field if the given value is not nil.
func (_u *RouteUpdate) SetNillablePublicURL(v *string) *RouteUpdate {
	if v != nil {
		_u.SetPublicURL(*v)
	}
	return _u
}

// SetPeerID sets the "peer_id" field.
func (_u *RouteUpdate) SetPeerID(v string) *RouteUpdate {
	_u.mutation.SetPeerID(v)
	return _u
}

// SetNillablePeerID sets the "peer_id" field if the given value is not nil.
func (_u *RouteUpdate) SetNillablePeerID(v *string) *RouteUpdate {
	if v != nil {
		_u.SetPeerID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RouteUpdate) SetStatus(v string) *RouteUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RouteUpdate) SetNillableStatus(v *string) *RouteUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RouteUpdate) SetUpdatedAt(v time.Time) *RouteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RouteUpdate) SetExpiresAt(v time.Time) *RouteUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RouteUpdate) SetNillableExpiresAt(v *time.Time) *RouteUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the RouteMutation object of the builder.
func (_u *RouteUpdate) Mutation() *RouteMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RouteUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RouteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RouteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RouteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RouteUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := route.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RouteUpdate) check() error {
	if v, ok := _u.mutation.Token(); ok {
		if err := route.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Route.token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NodeID(); ok {
		if err := route.NodeIDValidator(v); err != nil {
			return &ValidationError{Name: "node_id", err: fmt.Errorf(`ent: validator failed for field "Route.node_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetURL(); ok {
		if err := route.TargetURLValidator(v); err != nil {
			return &ValidationError{Name: "target_url", err: fmt.Errorf(`ent: validator failed for field "Route.target_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicURL(); ok {
		if err := route.PublicURLValidator(v); err != nil {
			return &ValidationError{Name: "public_url", err: fmt.Errorf(`ent: validator failed for field "Route.public_url": %w`, err)}
		}
	}
	return nil
}

func (_u *RouteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(route.Table, route.Columns, sqlgraph.NewFieldSpec(route.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(route.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(route.FieldNodeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetURL(); ok {
		_spec.SetField(route.FieldTargetURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicURL(); ok {
		_spec.SetField(route.FieldPublicURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeerID(); ok {
		_spec.SetField(route.FieldPeerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(route.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(route.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(route.FieldExpiresAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{route.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RouteUpdateOne is the builder for updating a single Route entity.
type RouteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RouteMutation
}

// SetToken sets the "token" field.
func (_u *RouteUpdateOne) SetToken(v string) *RouteUpdateOne {
	_u.mutation.SetToken(v)
	return _u
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (_u *RouteUpdateOne) SetNillableToken(v *string) *RouteUpdateOne {
	if v != nil {
		_u.SetToken(*v)
	}
	return _u
}

// SetNodeID sets the "node_id" field.
func (_u *RouteUpdateOne) SetNodeID(v string) *RouteUpdateOne {
	_u.mutation.SetNodeID(v)
	return _u
}

// SetNillableNodeID sets the "node_id" field if the given value is not nil.
func (_u *RouteUpdateOne) SetNillableNodeID(v *string) *RouteUpdateOne {
	if v != nil {
		_u.SetNodeID(*v)
	}
	return _u
}

// SetTargetURL sets the "target_url" field.
func (_u *RouteUpdateOne) SetTargetURL(v string) *RouteUpdateOne {
	_u.mutation.SetTargetURL(v)
	return _u
}

// SetNillableTargetURL sets the "target_url" field if the given value is not nil.
func (_u *RouteUpdateOne) SetNillableTargetURL(v *string) *RouteUpdateOne {
	if v != nil {
		_u.SetTargetURL(*v)
	}
	return _u
}

// SetPublicURL sets the "public_url" field.
func (_u *RouteUpdateOne) SetPublicURL(v string) *RouteUpdateOne {
	_u.mutation.SetPublicURL(v)
	return _u
}

// SetNillablePublicURL sets the "public_url" field if the given value is not nil.
func (_u *RouteUpdateOne) SetNillablePublicURL(v *string) *RouteUpdateOne {
	if v != nil {
		_u.SetPublicURL(*v)
	}
	return _u
}

// SetPeerID sets the "peer_id" field.
func (_u *RouteUpdateOne) SetPeerID(v string) *RouteUpdateOne {
	_u.mutation.SetPeerID(v)
	return _u
}

// SetNillablePeerID sets the "peer_id" field if the given value is not nil.
func (_u *RouteUpdateOne) SetNillablePeerID(v *string) *RouteUpdateOne {
	if v != nil {
		_u.SetPeerID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RouteUpdateOne) SetStatus(v string) *RouteUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RouteUpdateOne) SetNillableStatus(v *string) *RouteUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RouteUpdateOne) SetUpdatedAt(v time.Time) *RouteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *RouteUpdateOne) SetExpiresAt(v time.Time) *RouteUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *RouteUpdateOne) SetNillableExpiresAt(v *time.Time) *RouteUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// Mutation returns the RouteMutation object of the builder.
func (_u *RouteUpdateOne) Mutation() *RouteMutation {
	return _u.mutation
}

// Where appends a list predicates to the RouteUpdate builder.
func (_u *RouteUpdateOne) Where(ps ...predicate.Route) *RouteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RouteUpdateOne) Select(field string, fields ...string) *RouteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Route entity.
func (_u *RouteUpdateOne) Save(ctx context.Context) (*Route, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RouteUpdateOne) SaveX(ctx context.Context) *Route {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RouteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RouteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RouteUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := route.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RouteUpdateOne) check() error {
	if v, ok := _u.mutation.Token(); ok {
		if err := route.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Route.token": %w`, err)}
		}
	}
	if v, ok := _u.mutation.NodeID(); ok {
		if err := route.NodeIDValidator(v); err != nil {
			return &ValidationError{Name: "node_id", err: fmt.Errorf(`ent: validator failed for field "Route.node_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TargetURL(); ok {
		if err := route.TargetURLValidator(v); err != nil {
			return &ValidationError{Name: "target_url", err: fmt.Errorf(`ent: validator failed for field "Route.target_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicURL(); ok {
		if err := route.PublicURLValidator(v); err != nil {
			return &ValidationError{Name: "public_url", err: fmt.Errorf(`ent: validator failed for field "Route.public_url": %w`, err)}
		}
	}
	return nil
}

func (_u *RouteUpdateOne) sqlSave(ctx context.Context) (_node *Route, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(route.Table, route.Columns, sqlgraph.NewFieldSpec(route.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Route.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, route.FieldID)
		for _, f := range fields {
			if !route.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != route.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Token(); ok {
		_spec.SetField(route.FieldToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.NodeID(); ok {
		_spec.SetField(route.FieldNodeID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetURL(); ok {
		_spec.SetField(route.FieldTargetURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicURL(); ok {
		_spec.SetField(route.FieldPublicURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeerID(); ok {
		_spec.SetField(route.FieldPeerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(route.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(route.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(route.FieldExpiresAt, field.TypeTime, value)
	}
	_node = &Route{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{route.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
