// Code generated by ent, DO NOT EDIT.

package ent

import (
	"localshare/internal/store/ent/adminsession"
	"localshare/internal/store/ent/adminuser"
	"localshare/internal/store/ent/auditevent"
	"localshare/internal/store/ent/clustersetting"
	"localshare/internal/store/ent/node"
	"localshare/internal/store/ent/route"
	"localshare/internal/store/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	adminsessionFields := schema.AdminSession{}.Fields()
	_ = adminsessionFields
	// adminsessionDescSessionID is the schema descriptor for session_id field.
	adminsessionDescSessionID := adminsessionFields[0].Descriptor()
	// adminsession.SessionIDValidator is a validator for the "session_id" field. It is called by the builders before save.
	adminsession.SessionIDValidator = adminsessionDescSessionID.Validators[0].(func(string) error)
	// adminsessionDescUsername is the schema descriptor for username field.
	adminsessionDescUsername := adminsessionFields[1].Descriptor()
	// adminsession.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	adminsession.UsernameValidator = adminsessionDescUsername.Validators[0].(func(string) error)
	// adminsessionDescLastSeen is the schema descriptor for last_seen field.
	adminsessionDescLastSeen := adminsessionFields[3].Descriptor()
	// adminsession.DefaultLastSeen holds the default value on creation for the last_seen field.
	adminsession.DefaultLastSeen = adminsessionDescLastSeen.Default.(func() time.Time)
	// adminsessionDescCreatedAt is the schema descriptor for created_at field.
	adminsessionDescCreatedAt := adminsessionFields[4].Descriptor()
	// adminsession.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminsession.DefaultCreatedAt = adminsessionDescCreatedAt.Default.(func() time.Time)
	adminuserFields := schema.AdminUser{}.Fields()
	_ = adminuserFields
	// adminuserDescUsername is the schema descriptor for username field.
	adminuserDescUsername := adminuserFields[0].Descriptor()
	// adminuser.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	adminuser.UsernameValidator = adminuserDescUsername.Validators[0].(func(string) error)
	// adminuserDescPasswordHash is the schema descriptor for password_hash field.
	adminuserDescPasswordHash := adminuserFields[1].Descriptor()
	// adminuser.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	adminuser.PasswordHashValidator = adminuserDescPasswordHash.Validators[0].(func(string) error)
	// adminuserDescCreatedAt is the schema descriptor for created_at field.
	adminuserDescCreatedAt := adminuserFields[2].Descriptor()
	// adminuser.DefaultCreatedAt holds the default value on creation for the created_at field.
	adminuser.DefaultCreatedAt = adminuserDescCreatedAt.Default.(func() time.Time)
	// adminuserDescUpdatedAt is the schema descriptor for updated_at field.
	adminuserDescUpdatedAt := adminuserFields[3].Descriptor()
	// adminuser.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	adminuser.DefaultUpdatedAt = adminuserDescUpdatedAt.Default.(func() time.Time)
	// adminuser.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	adminuser.UpdateDefaultUpdatedAt = adminuserDescUpdatedAt.UpdateDefault.(func() time.Time)
	auditeventFields := schema.AuditEvent{}.Fields()
	_ = auditeventFields
	// auditeventDescActor is the schema descriptor for actor field.
	auditeventDescActor := auditeventFields[0].Descriptor()
	// auditevent.DefaultActor holds the default value on creation for the actor field.
	auditevent.DefaultActor = auditeventDescActor.Default.(string)
	// auditeventDescAction is the schema descriptor for action field.
	auditeventDescAction := auditeventFields[1].Descriptor()
	// auditevent.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditevent.ActionValidator = auditeventDescAction.Validators[0].(func(string) error)
	// auditeventDescTarget is the schema descriptor for target field.
	auditeventDescTarget := auditeventFields[2].Descriptor()
	// auditevent.DefaultTarget holds the default value on creation for the target field.
	auditevent.DefaultTarget = auditeventDescTarget.Default.(string)
	// auditeventDescCreatedAt is the schema descriptor for created_at field.
	auditeventDescCreatedAt := auditeventFields[4].Descriptor()
	// auditevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	auditevent.DefaultCreatedAt = auditeventDescCreatedAt.Default.(func() time.Time)
	clustersettingFields := schema.ClusterSetting{}.Fields()
	_ = clustersettingFields
	// clustersettingDescKey is the schema descriptor for key field.
	clustersettingDescKey := clustersettingFields[0].Descriptor()
	// clustersetting.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	clustersetting.KeyValidator = clustersettingDescKey.Validators[0].(func(string) error)
	// clustersettingDescValue is the schema descriptor for value field.
	clustersettingDescValue := clustersettingFields[1].Descriptor()
	// clustersetting.DefaultValue holds the default value on creation for the value field.
	clustersetting.DefaultValue = clustersettingDescValue.Default.(string)
	// clustersettingDescUpdatedAt is the schema descriptor for updated_at field.
	clustersettingDescUpdatedAt := clustersettingFields[2].Descriptor()
	// clustersetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	clustersetting.DefaultUpdatedAt = clustersettingDescUpdatedAt.Default.(func() time.Time)
	// clustersetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	clustersetting.UpdateDefaultUpdatedAt = clustersettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	nodeFields := schema.Node{}.Fields()
	_ = nodeFields
	// nodeDescNodeID is the schema descriptor for node_id field.
	nodeDescNodeID := nodeFields[0].Descriptor()
	// node.NodeIDValidator is a validator for the "node_id" field. It is called by the builders before save.
	node.NodeIDValidator = nodeDescNodeID.Validators[0].(func(string) error)
	// nodeDescSSHServer is the schema descriptor for ssh_server field.
	nodeDescSSHServer := nodeFields[1].Descriptor()
	// node.DefaultSSHServer holds the default value on creation for the ssh_server field.
	node.DefaultSSHServer = nodeDescSSHServer.Default.(string)
	// nodeDescPublicBaseURL is the schema descriptor for public_base_url field.
	nodeDescPublicBaseURL := nodeFields[2].Descriptor()
	// node.DefaultPublicBaseURL holds the default value on creation for the public_base_url field.
	node.DefaultPublicBaseURL = nodeDescPublicBaseURL.Default.(string)
	// nodeDescWeight is the schema descriptor for weight field.
	nodeDescWeight := nodeFields[3].Descriptor()
	// node.DefaultWeight holds the default value on creation for the weight field.
	node.DefaultWeight = nodeDescWeight.Default.(int)
	// node.WeightValidator is a validator for the "weight" field. It is called by the builders before save.
	node.WeightValidator = nodeDescWeight.Validators[0].(func(int) error)
	// nodeDescEnabled is the schema descriptor for enabled field.
	nodeDescEnabled := nodeFields[4].Descriptor()
	// node.DefaultEnabled holds the default value on creation for the enabled field.
	node.DefaultEnabled = nodeDescEnabled.Default.(bool)
	// nodeDescMaintenance is the schema descriptor for maintenance field.
	nodeDescMaintenance := nodeFields[5].Descriptor()
	// node.DefaultMaintenance holds the default value on creation for the maintenance field.
	node.DefaultMaintenance = nodeDescMaintenance.Default.(bool)
	// nodeDescMaxTunnels is the schema descriptor for max_tunnels field.
	nodeDescMaxTunnels := nodeFields[6].Descriptor()
	// node.DefaultMaxTunnels holds the default value on creation for the max_tunnels field.
	node.DefaultMaxTunnels = nodeDescMaxTunnels.Default.(int)
	// node.MaxTunnelsValidator is a validator for the "max_tunnels" field. It is called by the builders before save.
	node.MaxTunnelsValidator = nodeDescMaxTunnels.Validators[0].(func(int) error)
	// nodeDescCurrentTunnels is the schema descriptor for current_tunnels field.
	nodeDescCurrentTunnels := nodeFields[7].Descriptor()
	// node.DefaultCurrentTunnels holds the default value on creation for the current_tunnels field.
	node.DefaultCurrentTunnels = nodeDescCurrentTunnels.Default.(int)
	// node.CurrentTunnelsValidator is a validator for the "current_tunnels" field. It is called by the builders before save.
	node.CurrentTunnelsValidator = nodeDescCurrentTunnels.Validators[0].(func(int) error)
	// nodeDescMaxActiveConnections is the schema descriptor for max_active_connections field.
	nodeDescMaxActiveConnections := nodeFields[8].Descriptor()
	// node.DefaultMaxActiveConnections holds the default value on creation for the max_active_connections field.
	node.DefaultMaxActiveConnections = nodeDescMaxActiveConnections.Default.(int)
	// node.MaxActiveConnectionsValidator is a validator for the "max_active_connections" field. It is called by the builders before save.
	node.MaxActiveConnectionsValidator = nodeDescMaxActiveConnections.Validators[0].(func(int) error)
	// nodeDescActiveConnections is the schema descriptor for active_connections field.
	nodeDescActiveConnections := nodeFields[9].Descriptor()
	// node.DefaultActiveConnections holds the default value on creation for the active_connections field.
	node.DefaultActiveConnections = nodeDescActiveConnections.Default.(int)
	// node.ActiveConnectionsValidator is a validator for the "active_connections" field. It is called by the builders before save.
	node.ActiveConnectionsValidator = nodeDescActiveConnections.Validators[0].(func(int) error)
	// nodeDescRegion is the schema descriptor for region field.
	nodeDescRegion := nodeFields[10].Descriptor()
	// node.DefaultRegion holds the default value on creation for the region field.
	node.DefaultRegion = nodeDescRegion.Default.(string)
	// nodeDescToken is the schema descriptor for token field.
	nodeDescToken := nodeFields[11].Descriptor()
	// node.DefaultToken holds the default value on creation for the token field.
	node.DefaultToken = nodeDescToken.Default.(string)
	// nodeDescLastHeartbeat is the schema descriptor for last_heartbeat field.
	nodeDescLastHeartbeat := nodeFields[12].Descriptor()
	// node.DefaultLastHeartbeat holds the default value on creation for the last_heartbeat field.
	node.DefaultLastHeartbeat = nodeDescLastHeartbeat.Default.(func() time.Time)
	// nodeDescIsLocal is the schema descriptor for is_local field.
	nodeDescIsLocal := nodeFields[13].Descriptor()
	// node.DefaultIsLocal holds the default value on creation for the is_local field.
	node.DefaultIsLocal = nodeDescIsLocal.Default.(bool)
	// nodeDescCreatedAt is the schema descriptor for created_at field.
	nodeDescCreatedAt := nodeFields[14].Descriptor()
	// node.DefaultCreatedAt holds the default value on creation for the created_at field.
	node.DefaultCreatedAt = nodeDescCreatedAt.Default.(func() time.Time)
	// nodeDescUpdatedAt is the schema descriptor for updated_at field.
	nodeDescUpdatedAt := nodeFields[15].Descriptor()
	// node.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	node.DefaultUpdatedAt = nodeDescUpdatedAt.Default.(func() time.Time)
	// node.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	node.UpdateDefaultUpdatedAt = nodeDescUpdatedAt.UpdateDefault.(func() time.Time)
	routeFields := schema.Route{}.Fields()
	_ = routeFields
	// routeDescToken is the schema descriptor for token field.
	routeDescToken := routeFields[0].Descriptor()
	// route.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	route.TokenValidator = routeDescToken.Validators[0].(func(string) error)
	// routeDescNodeID is the schema descriptor for node_id field.
	routeDescNodeID := routeFields[1].Descriptor()
	// route.NodeIDValidator is a validator for the "node_id" field. It is called by the builders before save.
	route.NodeIDValidator = routeDescNodeID.Validators[0].(func(string) error)
	// routeDescTargetURL is the schema descriptor for target_url field.
	routeDescTargetURL := routeFields[2].Descriptor()
	// route.TargetURLValidator is a validator for the "target_url" field. It is called by the builders before save.
	route.TargetURLValidator = routeDescTargetURL.Validators[0].(func(string) error)
	// routeDescPublicURL is the schema descriptor for public_url field.
	routeDescPublicURL := routeFields[3].Descriptor()
	// route.PublicURLValidator is a validator for the "public_url" field. It is called by the builders before save.
	route.PublicURLValidator = routeDescPublicURL.Validators[0].(func(string) error)
	// routeDescPeerID is the schema descriptor for peer_id field.
	routeDescPeerID := routeFields[4].Descriptor()
	// route.DefaultPeerID holds the default value on creation for the peer_id field.
	route.DefaultPeerID = routeDescPeerID.Default.(string)
	// routeDescStatus is the schema descriptor for status field.
	routeDescStatus := routeFields[5].Descriptor()
	// route.DefaultStatus holds the default value on creation for the status field.
	route.DefaultStatus = routeDescStatus.Default.(string)
	// routeDescCreatedAt is the schema descriptor for created_at field.
	routeDescCreatedAt := routeFields[6].Descriptor()
	// route.DefaultCreatedAt holds the default value on creation for the created_at field.
	route.DefaultCreatedAt = routeDescCreatedAt.Default.(func() time.Time)
	// routeDescUpdatedAt is the schema descriptor for updated_at field.
	routeDescUpdatedAt := routeFields[7].Descriptor()
	// route.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	route.DefaultUpdatedAt = routeDescUpdatedAt.Default.(func() time.Time)
	// route.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	route.UpdateDefaultUpdatedAt = routeDescUpdatedAt.UpdateDefault.(func() time.Time)
}
