// Code generated by ent, DO NOT EDIT.

package route

import (
	"localshare/internal/store/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Route {
	return predicate.Route(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Route {
	return predicate.Route(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Route {
	return predicate.Route(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Route {
	return predicate.Route(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Route {
	return predicate.Route(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Route {
	return predicate.Route(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Route {
	return predicate.Route(sql.FieldLTE(FieldID, id))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldToken, v))
}

// NodeID applies equality check predicate on the "node_id" field. It's identical to NodeIDEQ.
func NodeID(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldNodeID, v))
}

// TargetURL applies equality check predicate on the "target_url" field. It's identical to TargetURLEQ.
func TargetURL(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldTargetURL, v))
}

// PublicURL applies equality check predicate on the "public_url" field. It's identical to PublicURLEQ.
func PublicURL(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldPublicURL, v))
}

// PeerID applies equality check predicate on the "peer_id" field. It's identical to PeerIDEQ.
func PeerID(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldPeerID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldUpdatedAt, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldExpiresAt, v))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.Route {
	return predicate.Route(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.Route {
	return predicate.Route(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.Route {
	return predicate.Route(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.Route {
	return predicate.Route(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.Route {
	return predicate.Route(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.Route {
	return predicate.Route(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.Route {
	return predicate.Route(sql.FieldContainsFold(FieldToken, v))
}

// NodeIDEQ applies the EQ predicate on the "node_id" field.
func NodeIDEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldNodeID, v))
}

// NodeIDNEQ applies the NEQ predicate on the "node_id" field.
func NodeIDNEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldNEQ(FieldNodeID, v))
}

// NodeIDIn applies the In predicate on the "node_id" field.
func NodeIDIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldIn(FieldNodeID, vs...))
}

// NodeIDNotIn applies the NotIn predicate on the "node_id" field.
func NodeIDNotIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldNotIn(FieldNodeID, vs...))
}

// NodeIDGT applies the GT predicate on the "node_id" field.
func NodeIDGT(v string) predicate.Route {
	return predicate.Route(sql.FieldGT(FieldNodeID, v))
}

// NodeIDGTE applies the GTE predicate on the "node_id" field.
func NodeIDGTE(v string) predicate.Route {
	return predicate.Route(sql.FieldGTE(FieldNodeID, v))
}

// NodeIDLT applies the LT predicate on the "node_id" field.
func NodeIDLT(v string) predicate.Route {
	return predicate.Route(sql.FieldLT(FieldNodeID, v))
}

// NodeIDLTE applies the LTE predicate on the "node_id" field.
func NodeIDLTE(v string) predicate.Route {
	return predicate.Route(sql.FieldLTE(FieldNodeID, v))
}

// NodeIDContains applies the Contains predicate on the "node_id" field.
func NodeIDContains(v string) predicate.Route {
	return predicate.Route(sql.FieldContains(FieldNodeID, v))
}

// NodeIDHasPrefix applies the HasPrefix predicate on the "node_id" field.
func NodeIDHasPrefix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasPrefix(FieldNodeID, v))
}

// NodeIDHasSuffix applies the HasSuffix predicate on the "node_id" field.
func NodeIDHasSuffix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasSuffix(FieldNodeID, v))
}

// NodeIDEqualFold applies the EqualFold predicate on the "node_id" field.
func NodeIDEqualFold(v string) predicate.Route {
	return predicate.Route(sql.FieldEqualFold(FieldNodeID, v))
}

// NodeIDContainsFold applies the ContainsFold predicate on the "node_id" field.
func NodeIDContainsFold(v string) predicate.Route {
	return predicate.Route(sql.FieldContainsFold(FieldNodeID, v))
}

// TargetURLEQ applies the EQ predicate on the "target_url" field.
func TargetURLEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldTargetURL, v))
}

// TargetURLNEQ applies the NEQ predicate on the "target_url" field.
func TargetURLNEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldNEQ(FieldTargetURL, v))
}

// TargetURLIn applies the In predicate on the "target_url" field.
func TargetURLIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldIn(FieldTargetURL, vs...))
}

// TargetURLNotIn applies the NotIn predicate on the "target_url" field.
func TargetURLNotIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldNotIn(FieldTargetURL, vs...))
}

// TargetURLGT applies the GT predicate on the "target_url" field.
func TargetURLGT(v string) predicate.Route {
	return predicate.Route(sql.FieldGT(FieldTargetURL, v))
}

// TargetURLGTE applies the GTE predicate on the "target_url" field.
func TargetURLGTE(v string) predicate.Route {
	return predicate.Route(sql.FieldGTE(FieldTargetURL, v))
}

// TargetURLLT applies the LT predicate on the "target_url" field.
func TargetURLLT(v string) predicate.Route {
	return predicate.Route(sql.FieldLT(FieldTargetURL, v))
}

// TargetURLLTE applies the LTE predicate on the "target_url" field.
func TargetURLLTE(v string) predicate.Route {
	return predicate.Route(sql.FieldLTE(FieldTargetURL, v))
}

// TargetURLContains applies the Contains predicate on the "target_url" field.
func TargetURLContains(v string) predicate.Route {
	return predicate.Route(sql.FieldContains(FieldTargetURL, v))
}

// TargetURLHasPrefix applies the HasPrefix predicate on the "target_url" field.
func TargetURLHasPrefix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasPrefix(FieldTargetURL, v))
}

// TargetURLHasSuffix applies the HasSuffix predicate on the "target_url" field.
func TargetURLHasSuffix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasSuffix(FieldTargetURL, v))
}

// TargetURLEqualFold applies the EqualFold predicate on the "target_url" field.
func TargetURLEqualFold(v string) predicate.Route {
	return predicate.Route(sql.FieldEqualFold(FieldTargetURL, v))
}

// TargetURLContainsFold applies the ContainsFold predicate on the "target_url" field.
func TargetURLContainsFold(v string) predicate.Route {
	return predicate.Route(sql.FieldContainsFold(FieldTargetURL, v))
}

// PublicURLEQ applies the EQ predicate on the "public_url" field.
func PublicURLEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldPublicURL, v))
}

// PublicURLNEQ applies the NEQ predicate on the "public_url" field.
func PublicURLNEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldNEQ(FieldPublicURL, v))
}

// PublicURLIn applies the In predicate on the "public_url" field.
func PublicURLIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldIn(FieldPublicURL, vs...))
}

// PublicURLNotIn applies the NotIn predicate on the "public_url" field.
func PublicURLNotIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldNotIn(FieldPublicURL, vs...))
}

// PublicURLGT applies the GT predicate on the "public_url" field.
func PublicURLGT(v string) predicate.Route {
	return predicate.Route(sql.FieldGT(FieldPublicURL, v))
}

// PublicURLGTE applies the GTE predicate on the "public_url" field.
func PublicURLGTE(v string) predicate.Route {
	return predicate.Route(sql.FieldGTE(FieldPublicURL, v))
}

// PublicURLLT applies the LT predicate on the "public_url" field.
func PublicURLLT(v string) predicate.Route {
	return predicate.Route(sql.FieldLT(FieldPublicURL, v))
}

// PublicURLLTE applies the LTE predicate on the "public_url" field.
func PublicURLLTE(v string) predicate.Route {
	return predicate.Route(sql.FieldLTE(FieldPublicURL, v))
}

// PublicURLContains applies the Contains predicate on the "public_url" field.
func PublicURLContains(v string) predicate.Route {
	return predicate.Route(sql.FieldContains(FieldPublicURL, v))
}

// PublicURLHasPrefix applies the HasPrefix predicate on the "public_url" field.
func PublicURLHasPrefix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasPrefix(FieldPublicURL, v))
}

// PublicURLHasSuffix applies the HasSuffix predicate on the "public_url" field.
func PublicURLHasSuffix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasSuffix(FieldPublicURL, v))
}

// PublicURLEqualFold applies the EqualFold predicate on the "public_url" field.
func PublicURLEqualFold(v string) predicate.Route {
	return predicate.Route(sql.FieldEqualFold(FieldPublicURL, v))
}

// PublicURLContainsFold applies the ContainsFold predicate on the "public_url" field.
func PublicURLContainsFold(v string) predicate.Route {
	return predicate.Route(sql.FieldContainsFold(FieldPublicURL, v))
}

// PeerIDEQ applies the EQ predicate on the "peer_id" field.
func PeerIDEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldPeerID, v))
}

// PeerIDNEQ applies the NEQ predicate on the "peer_id" field.
func PeerIDNEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldNEQ(FieldPeerID, v))
}

// PeerIDIn applies the In predicate on the "peer_id" field.
func PeerIDIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldIn(FieldPeerID, vs...))
}

// PeerIDNotIn applies the NotIn predicate on the "peer_id" field.
func PeerIDNotIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldNotIn(FieldPeerID, vs...))
}

// PeerIDGT applies the GT predicate on the "peer_id" field.
func PeerIDGT(v string) predicate.Route {
	return predicate.Route(sql.FieldGT(FieldPeerID, v))
}

// PeerIDGTE applies the GTE predicate on the "peer_id" field.
func PeerIDGTE(v string) predicate.Route {
	return predicate.Route(sql.FieldGTE(FieldPeerID, v))
}

// PeerIDLT applies the LT predicate on the "peer_id" field.
func PeerIDLT(v string) predicate.Route {
	return predicate.Route(sql.FieldLT(FieldPeerID, v))
}

// PeerIDLTE applies the LTE predicate on the "peer_id" field.
func PeerIDLTE(v string) predicate.Route {
	return predicate.Route(sql.FieldLTE(FieldPeerID, v))
}

// PeerIDContains applies the Contains predicate on the "peer_id" field.
func PeerIDContains(v string) predicate.Route {
	return predicate.Route(sql.FieldContains(FieldPeerID, v))
}

// PeerIDHasPrefix applies the HasPrefix predicate on the "peer_id" field.
func PeerIDHasPrefix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasPrefix(FieldPeerID, v))
}

// PeerIDHasSuffix applies the HasSuffix predicate on the "peer_id" field.
func PeerIDHasSuffix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasSuffix(FieldPeerID, v))
}

// PeerIDEqualFold applies the EqualFold predicate on the "peer_id" field.
func PeerIDEqualFold(v string) predicate.Route {
	return predicate.Route(sql.FieldEqualFold(FieldPeerID, v))
}

// PeerIDContainsFold applies the ContainsFold predicate on the "peer_id" field.
func PeerIDContainsFold(v string) predicate.Route {
	return predicate.Route(sql.FieldContainsFold(FieldPeerID, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Route {
	return predicate.Route(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Route {
	return predicate.Route(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Route {
	return predicate.Route(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Route {
	return predicate.Route(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Route {
	return predicate.Route(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Route {
	return predicate.Route(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Route {
	return predicate.Route(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Route {
	return predicate.Route(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Route {
	return predicate.Route(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Route {
	return predicate.Route(sql.FieldContainsFold(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Route {
	return predicate.Route(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Route {
	return predicate.Route(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Route {
	return predicate.Route(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Route {
	return predicate.Route(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldLTE(FieldUpdatedAt, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.Route {
	return predicate.Route(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.Route {
	return predicate.Route(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.Route {
	return predicate.Route(sql.FieldLTE(FieldExpiresAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Route) predicate.Route {
	return predicate.Route(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Route) predicate.Route {
	return predicate.Route(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Route) predicate.Route {
	return predicate.Route(sql.NotPredicates(p))
}
