// Code generated by ent, DO NOT EDIT.

package node

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the node type in the database.
	Label = "node"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNodeID holds the string denoting the node_id field in the database.
	FieldNodeID = "node_id"
	// FieldSSHServer holds the string denoting the ssh_server field in the database.
	FieldSSHServer = "ssh_server"
	// FieldPublicBaseURL holds the string denoting the public_base_url field in the database.
	FieldPublicBaseURL = "public_base_url"
	// FieldWeight holds the string denoting the weight field in the database.
	FieldWeight = "weight"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldMaintenance holds the string denoting the maintenance field in the database.
	FieldMaintenance = "maintenance"
	// FieldMaxTunnels holds the string denoting the max_tunnels field in the database.
	FieldMaxTunnels = "max_tunnels"
	// FieldCurrentTunnels holds the string denoting the current_tunnels field in the database.
	FieldCurrentTunnels = "current_tunnels"
	// FieldMaxActiveConnections holds the string denoting the max_active_connections field in the database.
	FieldMaxActiveConnections = "max_active_connections"
	// FieldActiveConnections holds the string denoting the active_connections field in the database.
	FieldActiveConnections = "active_connections"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// FieldLastHeartbeat holds the string denoting the last_heartbeat field in the database.
	FieldLastHeartbeat = "last_heartbeat"
	// FieldIsLocal holds the string denoting the is_local field in the database.
	FieldIsLocal = "is_local"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the node in the database.
	Table = "nodes"
)

// Columns holds all SQL columns for node fields.
var Columns = []string{
	FieldID,
	FieldNodeID,
	FieldSSHServer,
	FieldPublicBaseURL,
	FieldWeight,
	FieldEnabled,
	FieldMaintenance,
	FieldMaxTunnels,
	FieldCurrentTunnels,
	FieldMaxActiveConnections,
	FieldActiveConnections,
	FieldRegion,
	FieldToken,
	FieldLastHeartbeat,
	FieldIsLocal,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NodeIDValidator is a validator for the "node_id" field. It is called by the builders before save.
	NodeIDValidator func(string) error
	// DefaultSSHServer holds the default value on creation for the "ssh_server" field.
	DefaultSSHServer string
	// DefaultPublicBaseURL holds the default value on creation for the "public_base_url" field.
	DefaultPublicBaseURL string
	// DefaultWeight holds the default value on creation for the "weight" field.
	DefaultWeight int
	// WeightValidator is a validator for the "weight" field. It is called by the builders before save.
	WeightValidator func(int) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultMaintenance holds the default value on creation for the "maintenance" field.
	DefaultMaintenance bool
	// DefaultMaxTunnels holds the default value on creation for the "max_tunnels" field.
	DefaultMaxTunnels int
	// MaxTunnelsValidator is a validator for the "max_tunnels" field. It is called by the builders before save.
	MaxTunnelsValidator func(int) error
	// DefaultCurrentTunnels holds the default value on creation for the "current_tunnels" field.
	DefaultCurrentTunnels int
	// CurrentTunnelsValidator is a validator for the "current_tunnels" field. It is called by the builders before save.
	CurrentTunnelsValidator func(int) error
	// DefaultMaxActiveConnections holds the default value on creation for the "max_active_connections" field.
	DefaultMaxActiveConnections int
	// MaxActiveConnectionsValidator is a validator for the "max_active_connections" field. It is called by the builders before save.
	MaxActiveConnectionsValidator func(int) error
	// DefaultActiveConnections holds the default value on creation for the "active_connections" field.
	DefaultActiveConnections int
	// ActiveConnectionsValidator is a validator for the "active_connections" field. It is called by the builders before save.
	ActiveConnectionsValidator func(int) error
	// DefaultRegion holds the default value on creation for the "region" field.
	DefaultRegion string
	// DefaultToken holds the default value on creation for the "token" field.
	DefaultToken string
	// DefaultLastHeartbeat holds the default value on creation for the "last_heartbeat" field.
	DefaultLastHeartbeat func() time.Time
	// DefaultIsLocal holds the default value on creation for the "is_local" field.
	DefaultIsLocal bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Node queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByNodeID orders the results by the node_id field.
func ByNodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNodeID, opts...).ToFunc()
}

// BySSHServer orders the results by the ssh_server field.
func BySSHServer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSSHServer, opts...).ToFunc()
}

// ByPublicBaseURL orders the results by the public_base_url field.
func ByPublicBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicBaseURL, opts...).ToFunc()
}

// ByWeight orders the results by the weight field.
func ByWeight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeight, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByMaintenance orders the results by the maintenance field.
func ByMaintenance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaintenance, opts...).ToFunc()
}

// ByMaxTunnels orders the results by the max_tunnels field.
func ByMaxTunnels(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxTunnels, opts...).ToFunc()
}

// ByCurrentTunnels orders the results by the current_tunnels field.
func ByCurrentTunnels(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCurrentTunnels, opts...).ToFunc()
}

// ByMaxActiveConnections orders the results by the max_active_connections field.
func ByMaxActiveConnections(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxActiveConnections, opts...).ToFunc()
}

// ByActiveConnections orders the results by the active_connections field.
func ByActiveConnections(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActiveConnections, opts...).ToFunc()
}

// ByRegion orders the results by the region field.
func ByRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegion, opts...).ToFunc()
}

// ByToken orders the results by the token field.
func ByToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToken, opts...).ToFunc()
}

// ByLastHeartbeat orders the results by the last_heartbeat field.
func ByLastHeartbeat(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastHeartbeat, opts...).ToFunc()
}

// ByIsLocal orders the results by the is_local field.
func ByIsLocal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsLocal, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
