// Code generated by ent, DO NOT EDIT.

package node

import (
	"localshare/internal/store/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldID, id))
}

// NodeID applies equality check predicate on the "node_id" field. It's identical to NodeIDEQ.
func NodeID(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldNodeID, v))
}

// SSHServer applies equality check predicate on the "ssh_server" field. It's identical to SSHServerEQ.
func SSHServer(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldSSHServer, v))
}

// PublicBaseURL applies equality check predicate on the "public_base_url" field. It's identical to PublicBaseURLEQ.
func PublicBaseURL(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldPublicBaseURL, v))
}

// Weight applies equality check predicate on the "weight" field. It's identical to WeightEQ.
func Weight(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldWeight, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldEnabled, v))
}

// Maintenance applies equality check predicate on the "maintenance" field. It's identical to MaintenanceEQ.
func Maintenance(v bool) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldMaintenance, v))
}

// MaxTunnels applies equality check predicate on the "max_tunnels" field. It's identical to MaxTunnelsEQ.
func MaxTunnels(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldMaxTunnels, v))
}

// CurrentTunnels applies equality check predicate on the "current_tunnels" field. It's identical to CurrentTunnelsEQ.
func CurrentTunnels(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCurrentTunnels, v))
}

// MaxActiveConnections applies equality check predicate on the "max_active_connections" field. It's identical to MaxActiveConnectionsEQ.
func MaxActiveConnections(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldMaxActiveConnections, v))
}

// ActiveConnections applies equality check predicate on the "active_connections" field. It's identical to ActiveConnectionsEQ.
func ActiveConnections(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldActiveConnections, v))
}

// Region applies equality check predicate on the "region" field. It's identical to RegionEQ.
func Region(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldRegion, v))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldToken, v))
}

// LastHeartbeat applies equality check predicate on the "last_heartbeat" field. It's identical to LastHeartbeatEQ.
func LastHeartbeat(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldLastHeartbeat, v))
}

// IsLocal applies equality check predicate on the "is_local" field. It's identical to IsLocalEQ.
func IsLocal(v bool) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldIsLocal, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldUpdatedAt, v))
}

// NodeIDEQ applies the EQ predicate on the "node_id" field.
func NodeIDEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldNodeID, v))
}

// NodeIDNEQ applies the NEQ predicate on the "node_id" field.
func NodeIDNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldNodeID, v))
}

// NodeIDIn applies the In predicate on the "node_id" field.
func NodeIDIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldNodeID, vs...))
}

// NodeIDNotIn applies the NotIn predicate on the "node_id" field.
func NodeIDNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldNodeID, vs...))
}

// NodeIDGT applies the GT predicate on the "node_id" field.
func NodeIDGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldNodeID, v))
}

// NodeIDGTE applies the GTE predicate on the "node_id" field.
func NodeIDGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldNodeID, v))
}

// NodeIDLT applies the LT predicate on the "node_id" field.
func NodeIDLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldNodeID, v))
}

// NodeIDLTE applies the LTE predicate on the "node_id" field.
func NodeIDLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldNodeID, v))
}

// NodeIDContains applies the Contains predicate on the "node_id" field.
func NodeIDContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldNodeID, v))
}

// NodeIDHasPrefix applies the HasPrefix predicate on the "node_id" field.
func NodeIDHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldNodeID, v))
}

// NodeIDHasSuffix applies the HasSuffix predicate on the "node_id" field.
func NodeIDHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldNodeID, v))
}

// NodeIDEqualFold applies the EqualFold predicate on the "node_id" field.
func NodeIDEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldNodeID, v))
}

// NodeIDContainsFold applies the ContainsFold predicate on the "node_id" field.
func NodeIDContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldNodeID, v))
}

// SSHServerEQ applies the EQ predicate on the "ssh_server" field.
func SSHServerEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldSSHServer, v))
}

// SSHServerNEQ applies the NEQ predicate on the "ssh_server" field.
func SSHServerNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldSSHServer, v))
}

// SSHServerIn applies the In predicate on the "ssh_server" field.
func SSHServerIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldSSHServer, vs...))
}

// SSHServerNotIn applies the NotIn predicate on the "ssh_server" field.
func SSHServerNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldSSHServer, vs...))
}

// SSHServerGT applies the GT predicate on the "ssh_server" field.
func SSHServerGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldSSHServer, v))
}

// SSHServerGTE applies the GTE predicate on the "ssh_server" field.
func SSHServerGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldSSHServer, v))
}

// SSHServerLT applies the LT predicate on the "ssh_server" field.
func SSHServerLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldSSHServer, v))
}

// SSHServerLTE applies the LTE predicate on the "ssh_server" field.
func SSHServerLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldSSHServer, v))
}

// SSHServerContains applies the Contains predicate on the "ssh_server" field.
func SSHServerContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldSSHServer, v))
}

// SSHServerHasPrefix applies the HasPrefix predicate on the "ssh_server" field.
func SSHServerHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldSSHServer, v))
}

// SSHServerHasSuffix applies the HasSuffix predicate on the "ssh_server" field.
func SSHServerHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldSSHServer, v))
}

// SSHServerEqualFold applies the EqualFold predicate on the "ssh_server" field.
func SSHServerEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldSSHServer, v))
}

// SSHServerContainsFold applies the ContainsFold predicate on the "ssh_server" field.
func SSHServerContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldSSHServer, v))
}

// PublicBaseURLEQ applies the EQ predicate on the "public_base_url" field.
func PublicBaseURLEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldPublicBaseURL, v))
}

// PublicBaseURLNEQ applies the NEQ predicate on the "public_base_url" field.
func PublicBaseURLNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldPublicBaseURL, v))
}

// PublicBaseURLIn applies the In predicate on the "public_base_url" field.
func PublicBaseURLIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldPublicBaseURL, vs...))
}

// PublicBaseURLNotIn applies the NotIn predicate on the "public_base_url" field.
func PublicBaseURLNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldPublicBaseURL, vs...))
}

// PublicBaseURLGT applies the GT predicate on the "public_base_url" field.
func PublicBaseURLGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldPublicBaseURL, v))
}

// PublicBaseURLGTE applies the GTE predicate on the "public_base_url" field.
func PublicBaseURLGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldPublicBaseURL, v))
}

// PublicBaseURLLT applies the LT predicate on the "public_base_url" field.
func PublicBaseURLLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldPublicBaseURL, v))
}

// PublicBaseURLLTE applies the LTE predicate on the "public_base_url" field.
func PublicBaseURLLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldPublicBaseURL, v))
}

// PublicBaseURLContains applies the Contains predicate on the "public_base_url" field.
func PublicBaseURLContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldPublicBaseURL, v))
}

// PublicBaseURLHasPrefix applies the HasPrefix predicate on the "public_base_url" field.
func PublicBaseURLHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldPublicBaseURL, v))
}

// PublicBaseURLHasSuffix applies the HasSuffix predicate on the "public_base_url" field.
func PublicBaseURLHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldPublicBaseURL, v))
}

// PublicBaseURLEqualFold applies the EqualFold predicate on the "public_base_url" field.
func PublicBaseURLEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldPublicBaseURL, v))
}

// PublicBaseURLContainsFold applies the ContainsFold predicate on the "public_base_url" field.
func PublicBaseURLContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldPublicBaseURL, v))
}

// WeightEQ applies the EQ predicate on the "weight" field.
func WeightEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldWeight, v))
}

// WeightNEQ applies the NEQ predicate on the "weight" field.
func WeightNEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldWeight, v))
}

// WeightIn applies the In predicate on the "weight" field.
func WeightIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldWeight, vs...))
}

// WeightNotIn applies the NotIn predicate on the "weight" field.
func WeightNotIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldWeight, vs...))
}

// WeightGT applies the GT predicate on the "weight" field.
func WeightGT(v int) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldWeight, v))
}

// WeightGTE applies the GTE predicate on the "weight" field.
func WeightGTE(v int) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldWeight, v))
}

// WeightLT applies the LT predicate on the "weight" field.
func WeightLT(v int) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldWeight, v))
}

// WeightLTE applies the LTE predicate on the "weight" field.
func WeightLTE(v int) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldWeight, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldEnabled, v))
}

// MaintenanceEQ applies the EQ predicate on the "maintenance" field.
func MaintenanceEQ(v bool) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldMaintenance, v))
}

// MaintenanceNEQ applies the NEQ predicate on the "maintenance" field.
func MaintenanceNEQ(v bool) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldMaintenance, v))
}

// MaxTunnelsEQ applies the EQ predicate on the "max_tunnels" field.
func MaxTunnelsEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldMaxTunnels, v))
}

// MaxTunnelsNEQ applies the NEQ predicate on the "max_tunnels" field.
func MaxTunnelsNEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldMaxTunnels, v))
}

// MaxTunnelsIn applies the In predicate on the "max_tunnels" field.
func MaxTunnelsIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldMaxTunnels, vs...))
}

// MaxTunnelsNotIn applies the NotIn predicate on the "max_tunnels" field.
func MaxTunnelsNotIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldMaxTunnels, vs...))
}

// MaxTunnelsGT applies the GT predicate on the "max_tunnels" field.
func MaxTunnelsGT(v int) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldMaxTunnels, v))
}

// MaxTunnelsGTE applies the GTE predicate on the "max_tunnels" field.
func MaxTunnelsGTE(v int) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldMaxTunnels, v))
}

// MaxTunnelsLT applies the LT predicate on the "max_tunnels" field.
func MaxTunnelsLT(v int) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldMaxTunnels, v))
}

// MaxTunnelsLTE applies the LTE predicate on the "max_tunnels" field.
func MaxTunnelsLTE(v int) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldMaxTunnels, v))
}

// CurrentTunnelsEQ applies the EQ predicate on the "current_tunnels" field.
func CurrentTunnelsEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCurrentTunnels, v))
}

// CurrentTunnelsNEQ applies the NEQ predicate on the "current_tunnels" field.
func CurrentTunnelsNEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldCurrentTunnels, v))
}

// CurrentTunnelsIn applies the In predicate on the "current_tunnels" field.
func CurrentTunnelsIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldCurrentTunnels, vs...))
}

// CurrentTunnelsNotIn applies the NotIn predicate on the "current_tunnels" field.
func CurrentTunnelsNotIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldCurrentTunnels, vs...))
}

// CurrentTunnelsGT applies the GT predicate on the "current_tunnels" field.
func CurrentTunnelsGT(v int) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldCurrentTunnels, v))
}

// CurrentTunnelsGTE applies the GTE predicate on the "current_tunnels" field.
func CurrentTunnelsGTE(v int) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldCurrentTunnels, v))
}

// CurrentTunnelsLT applies the LT predicate on the "current_tunnels" field.
func CurrentTunnelsLT(v int) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldCurrentTunnels, v))
}

// CurrentTunnelsLTE applies the LTE predicate on the "current_tunnels" field.
func CurrentTunnelsLTE(v int) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldCurrentTunnels, v))
}

// MaxActiveConnectionsEQ applies the EQ predicate on the "max_active_connections" field.
func MaxActiveConnectionsEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldMaxActiveConnections, v))
}

// MaxActiveConnectionsNEQ applies the NEQ predicate on the "max_active_connections" field.
func MaxActiveConnectionsNEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldMaxActiveConnections, v))
}

// MaxActiveConnectionsIn applies the In predicate on the "max_active_connections" field.
func MaxActiveConnectionsIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldMaxActiveConnections, vs...))
}

// MaxActiveConnectionsNotIn applies the NotIn predicate on the "max_active_connections" field.
func MaxActiveConnectionsNotIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldMaxActiveConnections, vs...))
}

// MaxActiveConnectionsGT applies the GT predicate on the "max_active_connections" field.
func MaxActiveConnectionsGT(v int) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldMaxActiveConnections, v))
}

// MaxActiveConnectionsGTE applies the GTE predicate on the "max_active_connections" field.
func MaxActiveConnectionsGTE(v int) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldMaxActiveConnections, v))
}

// MaxActiveConnectionsLT applies the LT predicate on the "max_active_connections" field.
func MaxActiveConnectionsLT(v int) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldMaxActiveConnections, v))
}

// MaxActiveConnectionsLTE applies the LTE predicate on the "max_active_connections" field.
func MaxActiveConnectionsLTE(v int) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldMaxActiveConnections, v))
}

// ActiveConnectionsEQ applies the EQ predicate on the "active_connections" field.
func ActiveConnectionsEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldActiveConnections, v))
}

// ActiveConnectionsNEQ applies the NEQ predicate on the "active_connections" field.
func ActiveConnectionsNEQ(v int) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldActiveConnections, v))
}

// ActiveConnectionsIn applies the In predicate on the "active_connections" field.
func ActiveConnectionsIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldActiveConnections, vs...))
}

// ActiveConnectionsNotIn applies the NotIn predicate on the "active_connections" field.
func ActiveConnectionsNotIn(vs ...int) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldActiveConnections, vs...))
}

// ActiveConnectionsGT applies the GT predicate on the "active_connections" field.
func ActiveConnectionsGT(v int) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldActiveConnections, v))
}

// ActiveConnectionsGTE applies the GTE predicate on the "active_connections" field.
func ActiveConnectionsGTE(v int) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldActiveConnections, v))
}

// ActiveConnectionsLT applies the LT predicate on the "active_connections" field.
func ActiveConnectionsLT(v int) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldActiveConnections, v))
}

// ActiveConnectionsLTE applies the LTE predicate on the "active_connections" field.
func ActiveConnectionsLTE(v int) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldActiveConnections, v))
}

// RegionEQ applies the EQ predicate on the "region" field.
func RegionEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldRegion, v))
}

// RegionNEQ applies the NEQ predicate on the "region" field.
func RegionNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldRegion, v))
}

// RegionIn applies the In predicate on the "region" field.
func RegionIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldRegion, vs...))
}

// RegionNotIn applies the NotIn predicate on the "region" field.
func RegionNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldRegion, vs...))
}

// RegionGT applies the GT predicate on the "region" field.
func RegionGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldRegion, v))
}

// RegionGTE applies the GTE predicate on the "region" field.
func RegionGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldRegion, v))
}

// RegionLT applies the LT predicate on the "region" field.
func RegionLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldRegion, v))
}

// RegionLTE applies the LTE predicate on the "region" field.
func RegionLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldRegion, v))
}

// RegionContains applies the Contains predicate on the "region" field.
func RegionContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldRegion, v))
}

// RegionHasPrefix applies the HasPrefix predicate on the "region" field.
func RegionHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldRegion, v))
}

// RegionHasSuffix applies the HasSuffix predicate on the "region" field.
func RegionHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldRegion, v))
}

// RegionEqualFold applies the EqualFold predicate on the "region" field.
func RegionEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldRegion, v))
}

// RegionContainsFold applies the ContainsFold predicate on the "region" field.
func RegionContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldRegion, v))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.Node {
	return predicate.Node(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.Node {
	return predicate.Node(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.Node {
	return predicate.Node(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.Node {
	return predicate.Node(sql.FieldContainsFold(FieldToken, v))
}

// LastHeartbeatEQ applies the EQ predicate on the "last_heartbeat" field.
func LastHeartbeatEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldLastHeartbeat, v))
}

// LastHeartbeatNEQ applies the NEQ predicate on the "last_heartbeat" field.
func LastHeartbeatNEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldLastHeartbeat, v))
}

// LastHeartbeatIn applies the In predicate on the "last_heartbeat" field.
func LastHeartbeatIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldLastHeartbeat, vs...))
}

// LastHeartbeatNotIn applies the NotIn predicate on the "last_heartbeat" field.
func LastHeartbeatNotIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldLastHeartbeat, vs...))
}

// LastHeartbeatGT applies the GT predicate on the "last_heartbeat" field.
func LastHeartbeatGT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldLastHeartbeat, v))
}

// LastHeartbeatGTE applies the GTE predicate on the "last_heartbeat" field.
func LastHeartbeatGTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldLastHeartbeat, v))
}

// LastHeartbeatLT applies the LT predicate on the "last_heartbeat" field.
func LastHeartbeatLT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldLastHeartbeat, v))
}

// LastHeartbeatLTE applies the LTE predicate on the "last_heartbeat" field.
func LastHeartbeatLTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldLastHeartbeat, v))
}

// IsLocalEQ applies the EQ predicate on the "is_local" field.
func IsLocalEQ(v bool) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldIsLocal, v))
}

// IsLocalNEQ applies the NEQ predicate on the "is_local" field.
func IsLocalNEQ(v bool) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldIsLocal, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Node {
	return predicate.Node(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Node {
	return predicate.Node(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Node) predicate.Node {
	return predicate.Node(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Node) predicate.Node {
	return predicate.Node(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Node) predicate.Node {
	return predicate.Node(sql.NotPredicates(p))
}
