// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AdminSession is the predicate function for adminsession builders.
type AdminSession func(*sql.Selector)

// AdminUser is the predicate function for adminuser builders.
type AdminUser func(*sql.Selector)

// AuditEvent is the predicate function for auditevent builders.
type AuditEvent func(*sql.Selector)

// ClusterSetting is the predicate function for clustersetting builders.
type ClusterSetting func(*sql.Selector)

// Node is the predicate function for node builders.
type Node func(*sql.Selector)

// Route is the predicate function for route builders.
type Route func(*sql.Selector)
