# Minimal type stubs for asyncssh (Pylance can't resolve it otherwise).
# These cover only the API surface used by this project.

from typing import Any, Callable, List, Optional, TypeVar, Union

_T = TypeVar('_T')


class Error(Exception): ...


class ChannelOpenError(Error): ...


OPEN_CONNECT_FAILED = 2


class SSHServer:
    def connection_made(self, conn: 'SSHServerConnection') -> None: ...
    def connection_lost(self, exc: Optional[BaseException]) -> None: ...
    def begin_auth(self, username: str) -> bool: ...
    def password_auth_supported(self) -> bool: ...
    def new_sock_path(self) -> str: ...
    def unix_server_requested(self, listen_path: str) -> Any: ...
    def server_requested(self, listen_host: str, listen_port: int) -> Any: ...
    def env_received(self, name: str, value: str) -> Any: ...


class SSHConnection:
    def close(self) -> None: ...


class SSHServerConnection(SSHConnection):
    def set_extra_info(self, **kwargs: Any) -> None: ...
    def get_extra_info(self, name: str, default: Any = None) -> Any: ...
    def create_unix_connection(self, session_factory: Callable[..., Any], listen_path: str) -> Any: ...
    def create_connection(self, session_factory: Callable[..., Any], host: str, port: int, orig_host: str, orig_port: int) -> Any: ...


class SSHServerProcess:
    def get_extra_info(self, name: str) -> Any: ...
    def exit(self, status: int = 0) -> None: ...
    async def wait_closed(self) -> None: ...
    @property
    def command(self) -> Optional[str]: ...
    @property
    def stdout(self) -> Any: ...


async def create_server(server_factory: Union[type, Callable[..., Any]], *,
                        host: str, port: int,
                        server_host_keys: List[str], process_factory: Callable[..., Any],
                        agent_forwarding: bool = False,
                        allow_scp: bool = False,
                        keepalive_interval: int = 0) -> Any: ...


def generate_private_key(algorithm: str) -> 'SSHKey': ...


class SSHKey:
    def export_private_key(self) -> bytes: ...


class SSHListener:
    def close(self) -> None: ...
