services:
  localshare:
    image: hajiming/localshare:latest
    pull_policy: never
    container_name: localshare
    restart: unless-stopped
    environment:
      APP_SERVER_NAME: ${APP_SERVER_NAME:-localhost}
      TZ: Asia/Shanghai
      NOFILE_LIMIT: ${NOFILE_LIMIT:-200000}
    ulimits:
      nofile:
        soft: 200000
        hard: 200000
    ports:
      - "1022:1022"
      - "9000:80"
      - "9443:443"
    volumes:
      - ./config:/config
