# Minimal type stubs for aiohttp (Pylance can't resolve it otherwise).
# Covers only the API surface used by this project.

from typing import Any, Dict, Optional


class WSMsgType:
    TEXT = 1
    BINARY = 2
    ERROR = 3
    CLOSE = 4


class Request:
    @property
    def match_info(self) -> Dict[str, str]: ...
    @property
    def cookies(self) -> Dict[str, str]: ...
    async def json(self) -> Any: ...


class StreamResponse:
    def set_cookie(self, name: str, value: str, **kwargs: Any) -> 'StreamResponse': ...
    def del_cookie(self, name: str, **kwargs: Any) -> 'StreamResponse': ...


class Response(StreamResponse):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def set_cookie(self, name: str, value: str, **kwargs: Any) -> 'Response': ...
    def del_cookie(self, name: str, **kwargs: Any) -> 'Response': ...


class WebSocketResponse(StreamResponse):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    async def prepare(self, request: Request) -> 'WebSocketResponse': ...
    async def send_str(self, data: str) -> None: ...
    async def receive(self, timeout: Optional[float] = None) -> Any: ...
    async def close(self, *, code: int = 1000, message: bytes = b'') -> bool: ...
    @property
    def closed(self) -> bool: ...
    def __aiter__(self) -> Any: ...


def json_response(*args: Any, **kwargs: Any) -> Response: ...


class UrlMappingMatchInfo:
    def add_get(self, path: str, handler: Any) -> Any: ...
    def add_post(self, path: str, handler: Any) -> Any: ...
    def add_static(self, prefix: str, path: str, **kwargs: Any) -> Any: ...


class Application:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    @property
    def router(self) -> UrlMappingMatchInfo: ...


class AppRunner:
    def __init__(self, app: Application) -> None: ...
    async def setup(self) -> None: ...


class TCPSite:
    def __init__(self, runner: Any, host: str, port: int) -> None: ...
    async def start(self) -> None: ...
